### ISSUE TITLE
image is not available?

### ISSUE THREAD

**Issue by debiansid** [diginc/docker-pi-hole#10]
docker run -p 53:53/tcp -p 53:53/udp -p 80:80 --cap-add=NET_ADMIN -e piholeIP="$IP" --name pihole -d dockerhole_alpine
Unable to find image 'dockerhole_alpine:latest' locally
Pulling repository docker.io/library/dockerhole_alpine
docker: Error: image library/dockerhole_alpine not found.
See 'docker run --help'.

**Comment by diginc** [comment]
Sorry, that was the name of my docker-compose local build  it should be diginc/pi-hole for the image.  Updating docs now.
