### ISSUE TITLE
Something keeps resetting password

### ISSUE THREAD

**Issue by middleagedman** [diginc/docker-pi-hole#108]
Ok.. i thought I was losing my mind but I think every time the external cron runs to refresh the lists, the webpassword gets changed inside setupVars.  Yesterday I made a copy of the file after I had fixed the pihole password again, and today I see the file has changed somehow

└──╼ diff setupVars.conf setupVars.conf.orig
9d8
< WEBPASSWORD=98f40829900af94a8d4...snip
11a11
> WEBPASSWORD=cdc7a077f771937ea3a...snip

-rw-r--r--  1 root root  326 Feb 21 20:59 setupVars.conf.orig
-rw-r--r--  1 root root  326 Feb 22 15:51 setupVars.conf
-rw-r--r--  1 root root 3.0K Feb 22 15:51 adlists.default
-rw-------  1 root root 1.1M Feb 22 15:51 list.0.raw.githubusercontent.com.domains
-rw-r--r--  1 root root 2.3M Feb 22 15:51 list.preEventHorizon
-rw-r--r--  1 root root   45 Feb 22 15:51 local.list
-rw-r--r--  1 root root 3.5M Feb 22 15:51 gravity.list

What's weird is my docker.pihole cron doesn't have an entry to run at 3:51pm

59 1    * * 7   root    PATH="$PATH:/usr/local/bin/" docker exec $DOCKER_NAME pihole updateGravity > /dev/null

The only thing in my logs is 
Feb 22 15:50:36 trinity crond[1153]: (CRON) INFO (Shutting down)
Feb 22 15:51:26 trinity crond[878]: (CRON) INFO (RANDOM_DELAY will be scaled with factor 19% if used.)
Feb 22 15:51:26 trinity crond[878]: (CRON) INFO (running with inotify support)

Which I believe is anacron doing something.. 

All of my /etc/cron.* directories don't have anything in them other than docker.pihole cron and a logwatch/aide cron.

**Comment by middleagedman** [comment]
PS - docker.pihole cron job just has these entries

# Your container name goes here:
DOCKER_NAME=pihole
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# Pi-hole: Update the ad sources once a week on Sunday at 01:59
#          Download any updates from the adlists
59 1    * * 7   root    PATH="$PATH:/usr/local/bin/" docker exec $DOCKER_NAME pihole updateGravity > /dev/null

# Update docker-pi-hole by pulling the latest docker image ane re-creating your container.
# pihole software update commands are unsupported in docker!
#30 2    * * 7   root    PATH="$PATH:/usr/local/bin/" docker exec $DOCKER_NAME pihole updatePihole > /dev/null

# Pi-hole: Flush the log daily at 00:00 so it doesn't get out of control
#          Stats will be viewable in the Web interface thanks to the cron job above
00 00   * * *   root    PATH="$PATH:/usr/local/bin/" docker exec $DOCKER_NAME pihole flush > /dev/null

**Comment by diginc** [comment]
Does running either one of those docker execs manually strip WEBPASSWORD from setupVars.conf for you?

**Comment by middleagedman** [comment]
I figured it out!  It's when the container restarts.. it changes the password.. I guess 15:10 was the last time I restarted my linux box.. so the docker containers restarted themselves.. Now to dig inside of the pihole container and see what it's doing at boot.

**Comment by middleagedman** [comment]
Yup.. 
/start.sh
setup_web_password "$WEBPASSWORD"

So yea.. I didn't run my container with that ENV, since I assumed it stayed in the conf file.. but it looks like it just clears it out.   Maybe there should be an if statement if that ENV is defined, then set it?  Else dont?

**Comment by middleagedman** [comment]
Or I can just start passing the -e WEBPASSWORD which is probably the best thing.. But hey, if I can fall for this maybe this issue will help a new person later ;)

**Comment by diginc** [comment]
Hrrrm sorry about that, I forgot to document that the environment variable take precedence over manually set passwords on boot.  I guess there could be a condition for the empty WEBPASSWORD environment variable where I check if it is already set before removing it.

Related #106

**Comment by middleagedman** [comment]
No problem.. It's listed as "not required" in your docs, but yea, if someone does set it then ever decides to restart their container it might cause the same questions :)
