### ISSUE TITLE
Why cap-add NET_ADMIN ?

### ISSUE THREAD

**Issue by psi-4ward** [diginc/docker-pi-hole#110]
Hi,
I wondered why pi-hole needs the `NET_ADMIN` capabilities? DHCP?
I'v started the container without the cap-add and it seems to work fine.

**Comment by diginc** [comment]
I just followed the leader and did it because every other DNSMasq container also had it.

> DHCP

Looks like that the answer based on [this line in the source](https://github.com/dnsmasq/dnsmasq/blob/ce5732e84fc46d7f99c152f736cfb4ef5ec98a01/src/dnsmasq.c#L574)

**Comment by psi-4ward** [comment]
So we should take a note in the README, I'm sure most users don't use builtin DHCP

**Comment by diginc** [comment]
I'm actually pretty close to switching to it, in researching what it'd take I noted that `--net host` would also be required.

I think you're right that the default use case doesn't include DHCP.

Given these to facts, I'm thinking we could 1) yank net admin from the recommended start command 2) add a DHCP start command with it included and `--net=host` mode, along with some disclaimers about what net host mode does.
