### ISSUE TITLE
Cannot delete blacklist/whitelist items on alpine image

### ISSUE THREAD

**Issue by Rickkwa** [diginc/docker-pi-hole#119]
I am using `:alpine` docker tag.

After I click on the trash icon to delete an entry through the web UI, the animation runs fine but when I refresh the page the entry re-appears and isn't deleted.

I tried going into the container and manually ran `pihole -b -q -d facebook.com` which is the command located in `/var/www/html/admin/scripts/pi-hole/php/sub.php`.

Here are the results:
```
::: Removing facebook.com from /etc/pihole/blacklist.txt...
sed: unsupported command I
:::
::: Neutrino emissions detected...
:::
::: No custom adlist file detected, reading from default file... done!
:::
::: Using cached Event Horizon list...
::: 104117 unique domains trapped in the event horizon.
:::
::: Adding adlist sources to the whitelist... done!
::: Whitelisting 8 domains... done!
::: Blacklisting 2 domains... done!
::: Wildcard blocked domain: 1
::: Formatting domains into a HOSTS file... done!
:::
::: Cleaning up un-needed files... done!
:::
::: Refresh lists in dnsmasq... done!
::: DNS service is running
::: Pi-hole blocking is Enabled
```

The highlight from the above snippet is this: `sed: unsupported command I`

Looking in the file `/opt/pihole/list.sh`, I find where it runs the `sed` (in `RemoveDomain` function):
```
...
#Is it in the list? Logic follows that if its whitelisted it should not be blacklisted and vice versa
grep -Ex -q "${domain}" "${list}" > /dev/null 2>&1 || bool=false
if [[ "${bool}" == true ]]; then
    # Remove it from the other one
    echo "::: Removing $1 from $list..."
    # /I flag: search case-insensitive
    sed -i "/${domain}/Id" "${list}"
    reload=true
else
...
```

And indeed the error seems to come from here:
```
bash-4.3# sed -i "/facebook\.com/Id" "/etc/pihole/blacklist.txt"
sed: unsupported command I
```

I tried running a similar command outside of the container (in Ubuntu 16) and I didn't receive that error.

**Comment by Rickkwa** [comment]
Also worth mentioning that the `sed` inside the container comes from `BusyBox v1.26.2 (2017-02-21 17:41:44 GMT) multi-call binary.`.

**Comment by diginc** [comment]
I've started a local branch and am working on fixing this upstream in [pi-hole/pi-hole](https://github.com/pi-hole/pi-hole)
