### ISSUE TITLE
Is there a way to persist the blacklist wildcards?

### ISSUE THREAD

**Issue by Rickkwa** [diginc/docker-pi-hole#120]

**Comment by diginc** [comment]
Have you tried a docker volume directory for /etc/pihole/ ?

**Comment by Rickkwa** [comment]
The wildcards are not stored in /etc/pihole

**Comment by PromoFaux** [comment]
`/etc/dnsmasq.d/03-pihole-wildcard.conf`, at least, that is how it is on non-docker installs.

**Comment by diginc** [comment]
so making a volume out of /etc/dnsmasq.d/03-pihole-wildcard.conf should work.  Permissions maybe tricky however.

**Comment by Rickkwa** [comment]
Rather than permissions, I'm not sure that you can overwrite `03-pihole-wildcard.conf` from the container. Since the `sed` creates and temporary file and tries to move it to replace `03-pihole-wildcard.conf`. There may be an issue with the difference in inode since docker mounts are on the inode level.

**Comment by diginc** [comment]
s6-overlay has a [nice way of handling permissoins](https://github.com/just-containers/s6-overlay#fixing-ownership--permissions).  Take a look at any of linuxserver.io images PUID PGID env vars for a real world example of it in action...actually LS.io may have made  a custom script around s6-overlay, not 100% sure.

I'm aiming to complete the image init system refactor, switching from tini to s6, and include it with the upcoming pi-hole 3.0 release.

**Comment by diginc** [comment]
> There may be an issue with the difference in inode since docker mounts are on the inode level.

I'll write a new test for this and confirm wildcard updates work when volume mounted.

**Comment by diginc** [comment]
Since I'm way behind releasing 3.0 I'm settling for a quick manual test.  I had no problems adding a volume mount for `      - './03-pihole-wildcards.conf:/etc/dnsmasq.d/03-pihole-wildcard.conf'` (docker compose format), re-creating the container, and having my wildcard persist.

**Comment by diginc** [comment]
Deleting out of the wildcard file when the file it's self is a volume does not work.

Docker volume documentation says:

> Note: Many tools used to edit files including vi and sed --in-place may result in an inode change. Since Docker v1.1.0, this will produce an error such as “sed: cannot rename ./sedKdJ9Dy: Device or resource busy”. In the case where you want to edit the mounted file, it is often easiest to instead mount the parent directory.

making a volume of all of /etc/dnsmasq.d a volume seems to fix this.

**Comment by Rickkwa** [comment]
Going from my memory, I did try mounting the parent directory but then it gave an error about the config file `01-` (i don't remember the name of the file) missing. I would have to have that config on my host before I create the mount.. which isn't the most ideal.

**Comment by diginc** [comment]
probably 01-pihole.conf - somehow it seems to get re-created in the new version for me.  the development tags should be ready for testing.
