### ISSUE TITLE
Reset stats at midnight

### ISSUE THREAD

**Issue by 240ch** [diginc/docker-pi-hole#125]
I'm not sure but if I recall correctly, Pi-Hole running on a Raspberry Pi would reset all stats at midnight so when you check the Dashboard / "Queries over time" chart, you would always see the queries of the current day (so far). Could this be implemented in the docker-pi-hole too? Or does this interfere with #107 and you wouldn't want cron jobs to fire?

**Comment by mukimov** [comment]
@240ch If I understand you corectly, run cron from **host** machine
`00 00 * * * root PATH="$PATH:/usr/local/bin/" docker exec $DOCKER_NAME pihole flush > /dev/null`
will do the job, you can find this in docker-pi-hole.cron

**Comment by 240ch** [comment]
@mukimov wonderful, that works. Thank you very much. So I will set up the cron job in my host.

**Comment by diginc** [comment]
upcoming 3.0 will include cron inside the container per the request in #107 - This will replace the old cron on the host behavior recommended in my readme.
