### ISSUE TITLE
ARM version not working

### ISSUE THREAD

**Issue by theilgaard** [diginc/docker-pi-hole#131]
When trying to run the ARM tag of the project I get the following error:
```
~ > docker run diginc/pi-hole:arm
standard_init_linux.go:178: exec user process caused "exec format error"
```

Update: Sorry, I'm a silly person, I was on the wrong architecture. (x86)

**Comment by diginc** [comment]
New version just came out FYI.   I'm doing some doc updates to make arm vs x86 clearer too.

**Comment by BarnumD** [comment]
I'm running 4.2.2-1_armhf on a pi.  Getting the same error.
If I use docker run it works, but If I use the docker-compose similar to what's on https://hub.docker.com/r/pihole/pihole than I get this error.

**Comment by diginc** [comment]
Please open a new issue and follow the template @BarnumD
