### ISSUE TITLE
pihole.log not being written to

### ISSUE THREAD

**Issue by Inevitable** [diginc/docker-pi-hole#136]
On several completely fresh container creations, I've been experiencing this same issue.  Essentially pihole.log never gets written to at all.  Flushing logs updates the file modified timestamp, but only produces a single blank line in the log.  After that it once again is never updated or added to.

I've not carried forward any existing data into these new containers.  I'm not mounting the pihole.log, so I don't think it can be a permissions issue.

My environment is boot2docker running docker 1.12.3.  My run command is your example plus a macvlan to give the container an address on my network.  It properly responds to dns requests, and blocking is also functioning.

**Comment by diginc** [comment]
I think the volume for dnsmas.d broke this.  I should have a fix release running now based off [this commit](https://github.com/diginc/docker-pi-hole/pull/134/commits/78cb0c4a578557de6292dd4b5d8d7b75a3fc8f18)

**Comment by diginc** [comment]
If you have a 01-pihole.log in your dnsmasq.d volume folder you may need to remove it and have it get re-created by the new image's startup.

**Comment by Inevitable** [comment]
Confirming the latest commit resolves this issue.
