### ISSUE TITLE
unclear about ipv6 blocking

### ISSUE THREAD

**Issue by markschultz** [diginc/docker-pi-hole#143]
![screenshot from 2017-06-01 12-08-05](https://cloud.githubusercontent.com/assets/578776/26691548/27bf5b34-46c3-11e7-878c-6301a71d88b1.png)
from the above screenshot it looks like ipv4 requests are being blocked but ipv6 requests are not.

I've launched the container without any special ipv6 env vars

```
docker run -d \           
  --name pihole \         
  -p 53:53/tcp -p 53:53/udp -p 80:80 \               
  -v "${DOCKER_CONFIGS}/pihole/:/etc/pihole/" \      
  -v "${DOCKER_CONFIGS}/dnsmasq.d/:/etc/dnsmasq.d/" \                                                     
  -e DNS1="84.200.69.80" \                           
  -e DNS2="84.200.70.40" \                           
  -e ServerIP="${IP}" \   
  -e TZ="America/Chicago" \                          
  --restart=always \      
  diginc/pi-hole:alpine
```

I know my internet is ipv4 only if that makes a difference.

**Comment by diginc** [comment]
I believe if your computer's NIC has IPv6 turned on it'll perform nslookups for ipv6.  The fact your ISP or local network doesn't have IPv6 prevents this address from ever being used or routed anywhere though.

You could try passing in the ServerIPv6 env anyway and it might block them.  You'd still have 2 entries instead of 1 though which is a little annoying.  Perhaps there is a dnsmsaq setting to force disabled the IPv6 lookups.  I'll have to check into that.

**Comment by markschultz** [comment]
`ip addr show enp10s0` gives me
```
2: enp10s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000    
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff                                                    
    inet 192.168.2.100/24 brd 192.168.2.255 scope global dynamic enp10s0                                  
       valid_lft 69612sec preferred_lft 69612sec     
    inet6 fe80::d48f:5b78:5997:d144/64 scope link    
       valid_lft forever preferred_lft forever 
```
so i think you're right about my lan using ipv6 however if i use that address i get errors because i can't actually reach the internet via that address.

**Comment by markschultz** [comment]
using `-e IPv6=False` also doesn't seem to help.

**Comment by diginc** [comment]
Turning off ipv6 on your computer would probably prevent the lookup but you'd have to do that to all the computers.  disabling it in dnsmasq sounds nicer...

`-e IPv6=False` was just a small tweak for web interface listening on IPv6 breaking unread.  DNSMasq dynamically binds to whatever networks are available to it I believe but it's responses to IPv6 are maybe trickier to turn off than not binding to IPv6.  I pinged the pi-hole guys and am looking through http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html

**Comment by markschultz** [comment]
I think I'm still confused. I disabled IPv6 for my computer like you suggested but still saw the same behavior w/ IPv6. Looking closer at the logs I noticed that none of the DNS requests are traversing IPv6 its just that the request is for the AAAA record. So its a fully IPv4 connection from browser to upstream DNS server but pihole doesn't seem to be blocking the AAAA requests while it does block the A request for the same domains.

**Comment by diginc** [comment]
Setting `ServerIPv6` like the most recent documented `docker run` shows should make it show up as red.  

You'll still have duplicate entries.  I was trying to think of some clever way to stop the duplicate entries for non IPv6 enabled networks.  The pi-hole members seemed to think they could add an option to just stop logging them.

**Comment by markschultz** [comment]
ok so you would expect this to work?
```
docker run -d \           
  --name pihole \         
  -p 53:53/tcp -p 53:53/udp -p 80:80 \               
  -v "${DOCKER_CONFIGS}/pihole/:/etc/pihole/" \      
  -v "${DOCKER_CONFIGS}/dnsmasq.d/:/etc/dnsmasq.d/" \                                                     
  -e DNS1="84.200.69.80" \                           
  -e DNS2="84.200.70.40" \                           
  -e ServerIP="192.168.2.100" \   
  -e ServerIP="fe80::d48f:5b78:5997:d144" \   
  -e TZ="America/Chicago" \                          
  --restart=always \      
  diginc/pi-hole:alpine
```

**Comment by diginc** [comment]
Yup, that should at least turn the green IPv6 records red.  We can remove the log entries in a new release thanks to [this new feature in FTL.](https://github.com/pi-hole/FTL/issues/63)

**Comment by markschultz** [comment]
thank you for clearing this up.
