### ISSUE TITLE
Update to Pi-Hole 3.1

### ISSUE THREAD

**Issue by 4ipalino** [diginc/docker-pi-hole#146]
Hi, are ther eany plans to update this container?

**Comment by diginc** [comment]
I usually wait a couple days in case there are any hot fixes upstream releases.

**Comment by 4ipalino** [comment]
Oh that was a fast answer ^^, have time to wait for it :D

**Comment by middleagedman** [comment]
For what it's worth, I pulled the source down, edited the install.sh to use the latest versions, and docker build'd it.  Seems to work fine without any other additional modifications

**Comment by diginc** [comment]
There are some broken tests around `pihole disable` modifications.

**Comment by PromoFaux** [comment]
>soon

You dropped this: `™`

**Comment by redboyke** [comment]
pihole -up (image debian) running on synology
gives error:
Unable to complete update, contact Pi-hole
ash-4.3# docker exec pihole pihole -g
/usr/local/bin/pihole: line 79: /opt/pihole/gravity.sh: No such file or directory

**Comment by diginc** [comment]
The new update was [released](https://store.docker.com/community/images/diginc/pi-hole/tags) a while ago, sorry I forgot to close this issue.  Please review how to do a [docker style update](https://github.com/diginc/docker-pi-hole/blob/master/README.md#upgrading) by re-creating your container after pulling the new image
