### ISSUE TITLE
Error when configuring pihole in Docker for Windows 10

### ISSUE THREAD

**Issue by insanerwayner** [diginc/docker-pi-hole#147]
I have the container up and running but I am getting the following error when I go to reconfigure pihole:

`Fri Jun 23 10:46:21 AM C:\~> docker exec pihole pihole -r

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

:::
::: You are root.
OS distribution not supported`

Is this a compatibility issue or have I configured something wrong with my container?

**Comment by diginc** [comment]
Most likely because it is the alpine container and aline OS is not officially supported by their installer - I work around that by doing my own version of the installer.  What do you need configured that the [environment variables](https://github.com/diginc/docker-pi-hole/blob/master/README.md#environment-variables) do not support?

**Comment by insanerwayner** [comment]
Forgive me. Getting started with Docker and this is my first run at it. Actually the environment variables will give me what I need.  I was going to set to my companies internal DNS Servers. I see how that works now.

Perhaps this should be a new issue but since I am running this is in Windows the docker_run.sh will not work for me. How should I set the "-e ServerIP="${IP}"" Variable up?
If I'm understanding correctly the way you have it set up now:
Each time the container starts it is running the command to get the host machine's current IP address and setting that parameter?

So in theory if I were to set up another equivalent command for Windows to get the current IP address it should run that each time the container is started?

**Comment by diginc** [comment]
> So in theory if I were to set up another equivalent command for Windows to get the current IP address it should run that each time the container is started?

Correct.  Also if you have a static IP on your windows docker host, you could just hard code it into `-e ServerIP=`

**Comment by insanerwayner** [comment]
So what would the format on that parameter be for a Windows environment?

`-e ServerIP=${somecommand}`     ?

**Comment by diginc** [comment]
You might have to experiment a little your self, I 'googled' this real quick: https://duckduckgo.com/?q=powershell+v3+get+your+primary+IP

```
$ip = Test-Connection -ComputerName (hostname) -Count 1  | Select IPV4Address
```

**Comment by insanerwayner** [comment]
I've come up with this solution for getting the IP in PowerShell:
`(get-wmiobject win32_networkadapterconfiguration | Where { $_.ipaddress -ne $null -and $_.Description -match 'Gigabit Network Connection' }).ipaddress`

However where I'm confused is how to get the command properly formatted in the `docker run ... -e ServerIP=`  portion

I was thinking it would be something like:

`-e ServerIP=${powershell -noprofile -command "(get-wmiobject win32_networkadapterconfiguration | Where { $_.ipaddress -ne $null -and $_.Description -match 'Gigabit Network Connection' }).ipaddress"}`

**Comment by insanerwayner** [comment]
We're set to DHCP here. I could set myself up on a Static IP, but it would be nice to set this up since it is a laptop and it would be good for this to be dynamic as I move from place to place.
