### ISSUE TITLE
Error on connect web interface

### ISSUE THREAD

**Issue by atao** [diginc/docker-pi-hole#150]
Hello,
I'm using a synology with docker
i map 80 on 8080 on docker config
On http://192.168.0.10:8080/admin/
I have this message : Failed Host Check: 192.168.0.10 vs 0.0.0.0, 0:0:0:0:0:0, dockerpi.hole, pi.hole, localhost

Have you got any ideas?

**Comment by diginc** [comment]
You need to connect with one of the addresses on the left: 0.0.0.0, 0:0:0:0:0:0, dockerpi.hole, pi.hole, localhost

You can add your 192 IP to that list by setting VIRTUAL_HOST environment variable too.

**Comment by atao** [comment]
What should I indicate? Just this?
VIRTUAL_HOST 192.168.... {My computer ip} ?

I'm lost...

**Comment by diginc** [comment]
in the environment variables, VIRTUAL_HOST should equal 192.168.0.10

**Comment by atao** [comment]
Okay thanks!

**Comment by atao** [comment]
I test but not work... It's the same...

**Comment by diginc** [comment]
Did you destroy and re-create the docker container completely between changing the ENV?

If the error message still doesn't contain your 192.168 address on the right side of `vs` in `Failed Host Check: 192.168.0.10 vs 0.0.0.0, 0:0:0:0:0:0, dockerpi.hole, pi.hole, localhost` then your VIRTUAL_HOST is not set correctly.

Alternatively, you can also access it through http://pi.hole/admin/ if your DNS is already set to the pi hole.

**Comment by atao** [comment]
My dns is 192.168.0.10
Okay for http://pi.hole/admin/ but serveur listen on 8080...
I test http://pi.hole:8080/admin/ but not work...

**Comment by diginc** [comment]
Can you attach screenshots of your synology pi-hole docker configuration (especially environment variables), and maybe compare to the image / setup in this prior synology issue : https://github.com/diginc/docker-pi-hole/issues/135

**Comment by atao** [comment]
![firefox_2017-06-30_18-21-24](https://user-images.githubusercontent.com/9640884/27744726-f35b17ec-5dc0-11e7-858a-c0f5d4db9630.png)

**Comment by Mcat12** [comment]
What is the message when it does not work after going to `http://192.168.0.10:8080/admin`?

**Comment by atao** [comment]
![chrome_2017-06-30_18-27-20](https://user-images.githubusercontent.com/9640884/27744927-c5522628-5dc1-11e7-8243-b5af8be3abb5.png)

**Comment by Mcat12** [comment]
> `http://192.168.0.10:8080/admin`

Make sure to add the `:8080`

**Comment by atao** [comment]
oups mistake... sorry for the port...
![chrome_2017-06-30_18-29-10](https://user-images.githubusercontent.com/9640884/27745006-0f7c7460-5dc2-11e7-88cb-dab2a7174599.png)

**Comment by Mcat12** [comment]
What is the message for `http://pi.hole:8080/admin`?

**Comment by atao** [comment]
![chrome_2017-06-30_18-32-25](https://user-images.githubusercontent.com/9640884/27745131-7d111f44-5dc2-11e7-9454-63dc68b7ded3.png)

**Comment by Mcat12** [comment]
Make sure that that device is using Pi-hole.

**Comment by diginc** [comment]
You need SERVER_IP set as an environment variable too.  Please review the README: https://github.com/diginc/docker-pi-hole/blob/master/README.md

**Comment by atao** [comment]
It's okay, I did not have the right variables!
![firefox_2017-06-30_19-14-53](https://user-images.githubusercontent.com/9640884/27746841-175fb3de-5dc9-11e7-8bce-daf3f73fd1e9.png)

**Comment by nilee8** [comment]
Hi,

I'm having the same issue on a QNAP with the same docker container, however, the environment variables are set.


![image](https://user-images.githubusercontent.com/33500865/32578656-410afc82-c49b-11e7-9e8e-4b9d246cd890.png)

What am I missing?

**Comment by diginc** [comment]
Try 192.168.1.57/admin or pi.hole/admin

**Comment by nilee8** [comment]
Nevermind, I'm an idiot.

So the Virtual_Host and the ServerIP environment variable is the IP of the Pi-hole server. Not the workstation IP that you're trying to access the Pi-hole from.

This posed a problem on the QNAP as I had setup the docker container for DHCP and the environment variables for the container cannot be edited after creating the container. Which poses a problem as you don't know what the IP of the container is until after boot. 

In which case, I've got it sorted out now.

Apologies and thank you for the help.
