### ISSUE TITLE
Possible to lighttpd.conf server.bind = $ServerIP ?

### ISSUE THREAD

**Issue by FrozenDragoon** [diginc/docker-pi-hole#154]
Container created using the following string:
```
docker run -d \
--name pihole \
-h pihole \
--restart always \
-e INTERFACE=enp2s0f0:0 \
-e DNSMASQ_LISTENING=enp2s0f0:0 \
--net=host \
--cap-add=NET_ADMIN \
-v /srv/docker/dnsmasq:/etc/dnsmasq.d \
-v /srv/docker/pihole:/etc/pihole \
-v /var/log:/var/log \
-e TZ=America/Chicago \
-e WEBPASSWORD="snip" \
-e ServerIP=192.168.2.50 \
-e IPv6=False \
diginc/pi-hole:debian
```
----

My host has two interfaces, one that I am using for PiHole.  I also run an internal web server on this host, and for my application port 80 is required.

When running Pihole via normal install this is not a problem, as I just bound all pihole functions to the second interface. 

The container's Lighttpd automatically attempts to bind "*:80".  Is it possible to add the [server.bind](https://redmine.lighttpd.net/projects/1/wiki/Server_bindDetails) config line using the ServerIP environment variable? This will allow lighttpd to not attempt to overtake port 80 on every interface.

I have made the change manually, and can verify it works.  

Other than this, the container is working flawlessly so far.  Thanks for your work!

**Comment by FrozenDragoon** [comment]
```sed -i 's/server.port                 = 80/server.bind\t\t    = ${ServerIP}\nserver.port\t\t    = 80/' test.txt```
That works in pretty basic testing.  Maybe it could be added to ```docker-pi-hole/debian/start.sh```? 

This shouldn't cause a conflict due to ServerIP being a required variable. 

I'll see if I can put together a pull request, though I am very new to using git collaboratively.

**Comment by diginc** [comment]
Give the dev tags a shot to confirm it built in the cloud correctly (I forget that sometimes and just run my local docker builds).  Thanks for the report & fix.

**Comment by FrozenDragoon** [comment]
Pulled down the dev container and it all appears to be running smoothly, thanks for the quick response
