### ISSUE TITLE
exec format error on Alpine based images for ARM*

### ISSUE THREAD

**Issue by ulm0** [diginc/docker-pi-hole#178]
Testing alpine based images for arm, I noticed an `exec format error` issue , the cause might be the following line, since it's pulling a version for x86_64 only. 
https://github.com/diginc/docker-pi-hole/blob/825248fb864b3aa95969fbf6ce0b760d454277b3/install.sh#L29

Doing some more digging, I commented out that line to let the [Pi-hole script](https://raw.githubusercontent.com/pi-hole/pi-hole/v3.1.4/automated%20install/basic-install.sh) decide what the best choice was, once the ARM* images were built I tested them and faced a problem related to:
```sh
Starting pihole-FTL
./run: line 4: /usr/bin/pihole-FTL: No such file or directory 
```

Attached to the pihole container just to see if indeed the binary wasn't present, but it was...
```sh
bash-4.3# ls -ls /usr/bin/ | grep pihole
1312 -rwxr-xr-x    1 root     root       1342183 Oct 19 04:04 pihole-FTL
```

Maybe it was something related to ownership, so changed it to `chown pihole:root  /usr/bin/pihole-FTL`...hint: it was not.

Back to the `install.sh` script, I read it downloads a binary built with musl library, which is only officially available for x86_64 at the time of this writing, I thought it might be cause of the problem, so I built the docker image for x86_64 with the line commented out...tested it and voilà! pihole-FTL wasn't able to be found in that image either.
https://github.com/diginc/docker-pi-hole/blob/825248fb864b3aa95969fbf6ce0b760d454277b3/install.sh#L29

So one workaround would be building pihole-FTL with musl for ARM* (with an alpine image) or just opening an issue on the [FTL repo](https://github.com/pi-hole/FTL) requesting so.

In case they agree on building a version with musl library, something like this could be added to the  `install.sh` as used in the pi-hole install script.
```sh
if [[ $machine == arm* || $machine == *aarch* ]]; then
  # ARM
  if [[ "$lib" == "/lib/ld-linux-aarch64.so.1" ]]; then
    sed -i '/FTLinstall/ s/${binary}/pihole-FTL-aarch64-musl-linux-gnu/g' "${PIHOLE_INSTALL}"
  elif [[ "$lib" == "/lib/ld-linux-armhf.so.3" ]]; then
      if [ "$rev" -gt "6" ]; then
        sed -i '/FTLinstall/ s/${binary}/pihole-FTL-arm-musl-linux-gnueabihf/g' "${PIHOLE_INSTALL}"
      else
        sed -i '/FTLinstall/ s/${binary}/pihole-FTL-arm-musl-linux-gnueabi/g' "${PIHOLE_INSTALL}"
      fi
  else
    sed -i '/FTLinstall/ s/${binary}/pihole-FTL-arm-musl-linux-gnueabi/g' "${PIHOLE_INSTALL}"
  fi
elif [[ $machine == x86_64 ]]; then
  # 64bit
  sed -i '/FTLinstall/ s/${binary}/pihole-FTL-musl-linux-x86_64/g' "${PIHOLE_INSTALL}"
else 
  echo "Wrong architecture"
fi
```

**Comment by untalpierre** [comment]
cc/ @diginc

**Comment by diginc** [comment]
I think you're spot on that the FTL binary is the wrong arch.  I'm not yet sure what needs to be added to the [matrix of FTL cross compiling](https://github.com/pi-hole/FTL/edit/master/.travis.yml) for arm+musl 

Good timing too, I was just trying to uncover bugs causing the multiarch images to fail tests in my #169 work (not all tests were running before tonight's commits).   I haven't even hit the FTL failure case yet because dnsmasq doesn't start yet due to: `dnsmasq: failed to find list of interfaces: No such device` which I'll have to dig into more tomorrow.

**Comment by untalpierre** [comment]
I actually commented that line out in order to let the pi-hole script install the right binary according to the arch and it did, but then it showed the `no such file or directory` issue, will check the cross-compile matrix and see what i can get!

**Comment by untalpierre** [comment]
I actually commented that line out in order to let the pi-hole script install the right binary according to the arch and it did, but then it showed the `no such file or directory` issue, will check the cross-compile matrix and see what i can get!

**Comment by diginc** [comment]
https://github.com/pi-hole/FTL/pull/153

**Comment by untalpierre** [comment]
Good news is musl for arm is on the way. On the other hand, aarch64 image can be left apart because of the musl porting status; arm image can run on aarch64 system after all.

**Comment by diginc** [comment]
Removed alpine
