### ISSUE TITLE
"Lost Connection To API"

### ISSUE THREAD

**Issue by EgoAleSum** [diginc/docker-pi-hole#182]
I have set up Pi-Hole and the DNS server is working. However, the admin console isn't, and I am getting "Lost Connection To API". Additionally, FTL is marked as offline.

I'm using `diginc/pi-hole:alpine`, and I tried with `diginc/pi-hole:debian` too, latest releases.

Hardware is x86_64, running on Alpine 3.6.4 (that's the Docker host, not what's inside the container) and Docker CE 17.05. The Docker host runs inside a VM on ESXi (not that it should matter).

Logs show no error (but not even a success in starting FTL):

> ship:~# docker ps -a
> CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS                    PORTS               NAMES
> 1d1a0bb6388f        diginc/pi-hole:alpine   "/init"                  26 hours ago        Up 26 hours                                   boot_pi-hole_1
> 
> ship:~# docker logs boot_pi-hole_1
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] 01-resolver-resolv: applying... 
> [fix-attrs.d] 01-resolver-resolv: exited 0.
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 20-start.sh: executing... 
>  ::: Starting docker specific setup for docker diginc/pi-hole
> + [[ {PASSWORDHERE} == '' ]]
> + pihole -a -p {PASSWORDHERE} {PASSWORDHERE}
> New password set
> Using default DNS servers: 8.8.8.8 & 8.8.4.4
> DNSMasq binding to default interface: eth0
> Added ENV to php:
> [www]
> env[PATH] = /opt/pihole:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> env[PHP_ERROR_LOG] = /var/log/nginx/error.log
> env[ServerIP] = 10.3.2.3
> env[VIRTUAL_HOST] = 10.3.2.3
> Using IPv4 and IPv6
> dnsmasq: syntax check OK.
> [30-Oct-2017 04:20:19] NOTICE: configuration file /etc/php5/php-fpm.conf test is successful
> 
> nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
> nginx: configuration file /etc/nginx/nginx.conf test is successful
> ::: Testing DNSmasq config: ::: Testing PHP-FPM config: ::: Testing NGINX config: ::: All config checks passed, starting ...
> ::: Docker start setup complete - beginning s6 services
> :::
> ::: Neutrino emissions detected...
> :::
> ::: Pulling source lists into range... done!
> :::
> ::: Getting raw.githubusercontent.com list... done
> :::   Status: Success (OK)
> :::   List updated, transport successful!
> ::: Getting mirror1.malwaredomains.com list... done
> :::   Status: Not modified
> :::   No changes detected, transport skipped!
> ::: Getting sysctl.org list... done
> :::   Status: Not modified
> :::   No changes detected, transport skipped!
> ::: Getting zeustracker.abuse.ch list... done
> :::   Status: Not modified
> :::   No changes detected, transport skipped!
> ::: Getting s3.amazonaws.com list... done
> :::   Status: Not modified
> :::   No changes detected, transport skipped!
> ::: Getting s3.amazonaws.com list... done
> :::   Status: Not modified
> :::   No changes detected, transport skipped!
> ::: Getting hosts-file.net list... done
> :::   Status: Not modified
> :::   No changes detected, transport skipped!
> ::: 
> ::: Aggregating list of domains... done!
> ::: Formatting list of domains to remove comments.... done!
> ::: 133360 domains being pulled in by gravity...
> ::: Removing duplicate domains.... done!
> ::: 110127 unique domains trapped in the event horizon.
> :::
> ::: Adding adlist sources to the whitelist... done!
> ::: Whitelisting 7 domains... done!
> ::: Nothing to blacklist!
> ::: No wildcards used!
> ::: Formatting domains into a HOSTS file...::: Nothing to blacklist!
>  done!
> :::
> ::: Cleaning up un-needed files... done!
> :::
> ::: Refresh lists in dnsmasq...s6 service not found for dnsmasq, exiting...
>  done!
> ::: DNS service is running
> ::: Pi-hole blocking is Enabled
> [cont-init.d] 20-start.sh: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> Starting php-fpm
> Starting pihole-FTL
> Starting dnsmasq
> Starting crond
> Starting nginx
> [services.d] done.
> dnsmasq: started, version 2.78 cachesize 10000
> dnsmasq: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
> dnsmasq: using nameserver 8.8.4.4#53
> dnsmasq: using nameserver 8.8.8.8#53
> dnsmasq: read /etc/hosts - 7 addresses
> dnsmasq: failed to load names from /etc/pihole/black.list: No such file or directory
> dnsmasq: read /etc/pihole/local.list - 2 addresses
> dnsmasq: read /etc/pihole/gravity.list - 110127 addresses
> dnsmasq: read /etc/dns/lan.list - 13 addresses

(Rest of logs show a ton of DNS queries, so I'm truncating them)

**Comment by diginc** [comment]
All of the services seem to have launched without error according to your log.

```
[services.d] starting services
Starting php-fpm
Starting pihole-FTL
Starting dnsmasq
Starting crond
Starting nginx
```

could you check if the logs have FTL errors with:
```
docker logs pihole 2>&1 | grep "FTL"
``` 
(no errors should probably just show starting)

and if the FTL service is still running with:

```
docker exec pihole ps -ef | grep FTL
  566 root       0:00 s6-supervise pihole-FTL
  589 root       0:44 pihole-FTL no-daemon
```

That will hopefully gets enough info to explain what is happening here.

**Comment by diginc** [comment]
Not having any luck reproducing this sorry.  My host is a little different but as you stated about your hypervisor it really shouldn't matter.

I deleted my production pi-hole container, made sure I had pulled the latest uploaded version of alpine tag, deleted my two volume folders for /etc/pihole and /etc/dnsmasq.d off my host, and everything seemed operational on the web interface.

**Comment by EgoAleSum** [comment]
@diginc running `docker logs pihole 2>&1 | grep "FTL"` returns nothing.

Two thoughts: my host is Alpine Linux (that's where the Docker daemon is installed). It's unlikely, but maybe that's what's causing the issues?

Also, I have a "not-completely-standard" network setup for Docker, as each container is connected to a Docker network using macvlan. Again, I can't really see how this could be a problem, but here's how I launch the container:

First I create the macvlan:

````sh
$ docker network create -d macvlan --subnet=10.3.0.0/16 --gateway=10.3.0.1 -o parent=eth1 containernet
````

Then I launch the container with this compose file:

````yaml
version: '3.1'

services:
  pi-hole:
    image: diginc/pi-hole:alpine
    networks:
      containernet:
        ipv4_address: 10.3.2.3
    restart: always
    ports:
      - '80:80'
      - '53:53/tcp'
      - '53:53/udp'
    environment:
       - 'ServerIP=10.3.2.3'
       - 'TZ=America/Los_Angeles'
       - 'WEBPASSWORD=password-goes-here'
    volumes:
      - '/etc/docker/pihole:/etc/pihole'
      - '/etc/docker/dnsmasq:/etc/dnsmasq.d'
      - '/etc/docker/dns:/etc/dns'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  containernet:
    external:
      name: containernet
````

**Comment by diginc** [comment]
is FTL running or can you manually start it and see if it crashes out or anything like that?

`docker-compose exec pi-hole pihole-FTL debug` hopefully launches it manually in the foreground for your stack.

**Comment by EgoAleSum** [comment]
So this is what I've done:

````
ship:~# docker ps -a
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS                  PORTS               NAMES
c6d325a1a5a1        diginc/pi-hole:alpine   "/init"                  4 days ago          Up 4 days                                   boot_pi-hole_1
ship:~# docker exec boot_pi-hole_1 pihole-FTL debug
[2017-11-05 00:05:33.028] ########## FTL started! ##########
[2017-11-05 00:05:33.028] FTL branch: (no branch)
[2017-11-05 00:05:33.028] FTL hash: v2.11.1
[2017-11-05 00:05:33.028] FTL date: 2017-10-08 12:35:40 -0700
[2017-11-05 00:05:33.028] FTL user: root
[2017-11-05 00:05:33.028] Notice: Found no readable FTL config file
[2017-11-05 00:05:33.028]         Using default settings
[2017-11-05 00:05:33.028] Starting config file parsing
[2017-11-05 00:05:33.028]    SOCKET_LISTENING: only local
[2017-11-05 00:05:33.028]    TIMEFRAME: Rolling 24h
[2017-11-05 00:05:33.028]    QUERY_DISPLAY: Show queries
[2017-11-05 00:05:33.028]    AAAA_QUERY_ANALYSIS: Show AAAA queries
[2017-11-05 00:05:33.028]    MAXDBDAYS: max age for stored queries is 365 days
[2017-11-05 00:05:33.028] Finished config file parsing
[2017-11-05 00:05:33.028] PID of FTL process: 10163
[2017-11-05 00:05:33.040] Gravity list entries: 110138
[2017-11-05 00:05:33.040] No blacklist present
[2017-11-05 00:05:33.040] No wildcard blocking list present
[2017-11-05 00:05:33.041] Database initialized
[2017-11-05 00:05:33.041] Starting initial log file parsing
[2017-11-05 00:05:33.041] Warning: Reading of rotated log file /var/log/pihole.log.1 failed
[2017-11-05 00:05:33.041] Reading from /var/log/pihole.log (rw-r--r--)
[2017-11-05 00:05:33.041] Notice: Increasing forwarded struct size from 0 to 4 (188.00 B)
[2017-11-05 00:05:33.041]         at query time: Oct 31 06:19:48
[2017-11-05 00:05:33.700] New forward server: 8.8.4.4 google-public-dns-b.google.com (0/4)
[2017-11-05 00:05:33.700] Notice: Increasing overTime struct size from 0 to 100 (4.23 KB)
[2017-11-05 00:05:33.700]         at query time: Oct 31 06:19:48
[2017-11-05 00:05:33.727] New forward server: 8.8.8.8 google-public-dns-a.google.com (1/4)
[2017-11-05 00:05:33.968] Notice: Increasing overTime struct size from 100 to 200 (9.27 KB)
[2017-11-05 00:05:33.968]         at query time: Oct 31 22:40:24
[2017-11-05 00:05:34.201] Notice: Increasing overTime struct size from 200 to 300 (14.27 KB)
[2017-11-05 00:05:34.201]         at query time: Nov  1 15:20:21
[2017-11-05 00:05:34.376] Notice: Increasing overTime struct size from 300 to 400 (19.27 KB)
[2017-11-05 00:05:34.376]         at query time: Nov  2 08:00:17
[2017-11-05 00:05:34.519] Notice: Increasing overTime struct size from 400 to 500 (24.27 KB)
[2017-11-05 00:05:34.519]         at query time: Nov  3 00:40:11
[2017-11-05 00:05:34.673] Notice: Increasing overTime struct size from 500 to 600 (29.27 KB)
[2017-11-05 00:05:34.673]         at query time: Nov  3 18:18:12
[2017-11-05 00:05:34.675] Notice: Increasing queries struct size from 0 to 10000 (349.44 KB)
[2017-11-05 00:05:34.675]         at query time: Nov  4 00:05:43
[2017-11-05 00:05:34.675] Notice: Increasing domains struct size from 0 to 1000 (381.44 KB)
[2017-11-05 00:05:34.675]         at query time: Nov  4 00:05:43
[2017-11-05 00:05:34.675] New domain: ssl.google-analytics.com (1 - 0/1000)
[2017-11-05 00:05:34.675] Notice: Increasing clients struct size from 0 to 10 (381.70 KB)
[2017-11-05 00:05:34.675]         at query time: Nov  4 00:05:43
[2017-11-05 00:05:34.676] New client: 10.1.254.200 10.1.254.200 (0/10)
[2017-11-05 00:05:34.676] New domain: imap.gmail.com (2 - 1/1000)
[2017-11-05 00:05:34.676] New domain: webpoolsn23a06.infra.lync.com (2 - 2/1000)
[2017-11-05 00:05:34.676] New domain: lyncdiscoverinternal.microsoft.com (2 - 3/1000)
[2017-11-05 00:05:34.676] New domain: 10.client-channel.google.com (2 - 4/1000)
[2017-11-05 00:05:34.677] New client: 10.1.254.134 10.1.254.134 (1/10)

[.... TRUNCATED SOME LINES SHOWING "New domain", etc]

[2017-11-05 00:05:34.992] Finished initial log file parsing
[2017-11-05 00:05:34.992]  -> Total DNS queries: 8992
[2017-11-05 00:05:34.992]  -> Cached DNS queries: 1537
[2017-11-05 00:05:34.992]  -> Blocked DNS queries: 265
[2017-11-05 00:05:34.992]  -> Unknown DNS queries: 41
[2017-11-05 00:05:34.992]  -> Unique domains: 1921
[2017-11-05 00:05:34.992]  -> Unique clients: 4
[2017-11-05 00:05:34.992] Successfully accessed setupVars.conf
[2017-11-05 00:05:34.992] Error on binding on port 4711
[2017-11-05 00:05:34.993] Listening on port 4712 for incoming connections
[2017-11-05 00:06:00.055] Notice: Queries stored in DB: 6
[2017-11-05 00:07:00.090] Notice: Queries stored in DB: 
````

Apparently it can't bind to port 4711, but maybe that's because there's already one FTL running? In any case, FTL still doesn't work.

**Comment by diginc** [comment]
Yeah I got the same thing when I launched a 2nd instance of FTL in debug mode.  If FTL is running and listening on 4711 then maybe the admin interface just cannot connect to FTL for some reason (custom network?)

Based of a [search of the Admin source](https://github.com/pi-hole/AdminLTE/search?utf8=%E2%9C%93&q=connectFTL&type=) it is connecting to 127.0.0.1:4711 .

This should show if you can connect to FTL inside to that same interface+port through bash.

```
$ docker-compose exec pihole  nc -w1 -z 127.0.0.1 4711 && echo connected
connected
```

**Comment by EgoAleSum** [comment]
What connects to the FTL server, the pi-hole server, or my laptop directly? In the first case, if it's connecting to 127.0.0.1:4711, there shouldn't be anything blocking it; in the latter, then the firewall might be blocking that...

**Comment by EgoAleSum** [comment]
Running the command you suggested:

````sh
# docker exec boot_pi-hole_1 nc -w1 -z 127.0.0.1 4711 && echo connected
connected
````

Also, I've opened the port 4711 on 10.3.2.3 on the firewall, from any client, but it's not working.

**Comment by Mcat12** [comment]
The Pi-hole connects via localhost (PHP)

**Comment by diginc** [comment]
"Lost Connection To API" comes from PHP web admin trying to connect to FTL 127.0.0.1:4711 - all of this inside the container.  I'm confused why PHP wouldn't be able to connect while that bash command line could...

**Comment by EgoAleSum** [comment]
@diginc yes, I fully agree. There's definitely FTL running, as per:

````sh
# docker exec -it boot_pi-hole_1 netstat -an
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN      
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      
tcp        0      0 127.0.0.11:43007        0.0.0.0:*               LISTEN      
tcp        0      0 127.0.0.1:4711          0.0.0.0:*               LISTEN      
tcp        0      0 127.0.0.1:9000          127.0.0.1:43538         TIME_WAIT   
tcp        0      0 127.0.0.1:9000          127.0.0.1:43526         TIME_WAIT   
tcp        0      0 127.0.0.1:42440         127.0.0.1:4711          TIME_WAIT   
tcp        0      0 127.0.0.1:9000          127.0.0.1:43532         TIME_WAIT   
tcp        0      0 10.3.2.3:80             10.1.254.134:57378      ESTABLISHED 
tcp        0      0 127.0.0.1:9000          127.0.0.1:43536         TIME_WAIT   
tcp        0      0 127.0.0.1:9000          127.0.0.1:43534         TIME_WAIT   
tcp        0      0 127.0.0.1:9000          127.0.0.1:43530         TIME_WAIT   
tcp        0      0 :::80                   :::*                    LISTEN      
tcp        0      0 :::53                   :::*                    LISTEN      
udp        0      0 0.0.0.0:53              0.0.0.0:*                           
udp        0      0 127.0.0.11:36269        0.0.0.0:*                           
udp        0      0 :::53                   :::*                                
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node Path
unix  3      [ ]         STREAM     CONNECTED     1243100 P1243101
unix  3      [ ]         STREAM     CONNECTED     1243085 P1243086
unix  3      [ ]         STREAM     CONNECTED     1243086 P1243085
unix  3      [ ]         STREAM     CONNECTED     1243101 P1243100
````

Could this be because of the macvlan network?

**Comment by Mcat12** [comment]
Have you tried running it exactly as @diginc specifies in his container readme? It is most likely something outside of the container, so it might be the macvlan network.

**Comment by EgoAleSum** [comment]
Ok I've tried following the README, running the container without the macvlan, and FTL is still not working. Wondering at this point if it's because I'm using Alpine as Docker host?

````
ship:~# export IP="$(ip route get 8.8.8.8 | awk '{ print $NF; exit }')"
ship:~# docker run \
>     --rm \
>     --name pihole \
>     -p 53:53/tcp -p 53:53/udp -p 80:80 \
>     -e ServerIP="${IP}" \
>     diginc/pi-hole:alpine
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific setup for docker diginc/pi-hole
Assigning random password: ToCIpgIP
+ [[ ToCIpgIP == '' ]]
+ pihole -a -p ToCIpgIP ToCIpgIP
New password set
Using default DNS servers: 8.8.8.8 & 8.8.4.4
DNSMasq binding to default interface: eth0
Added ENV to php:
[www]
env[PATH] = /opt/pihole:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
env[PHP_ERROR_LOG] = /var/log/nginx/error.log
env[ServerIP] = 10.3.1.1
env[VIRTUAL_HOST] = 10.3.1.1
Using IPv4 and IPv6
::: Testing DNSmasq config: dnsmasq: syntax check OK.
::: Testing PHP-FPM config: [05-Nov-2017 04:09:32] NOTICE: configuration file /etc/php5/php-fpm.conf test is successful

::: Testing NGINX config: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
::: All config checks passed, starting ...
::: Docker start setup complete - beginning s6 services
:::
::: Neutrino emissions detected...
:::
::: Pulling source lists into range... done!
:::
::: Getting raw.githubusercontent.com list... done
:::   Status: Success (OK)
:::   List updated, transport successful!
::: Getting mirror1.malwaredomains.com list... done
:::   Status: Success (OK)
:::   List updated, transport successful!
::: Getting sysctl.org list... done
:::   Status: Success (OK)
:::   List updated, transport successful!
::: Getting zeustracker.abuse.ch list... done
:::   Status: Success (OK)
:::   List updated, transport successful!
::: Getting s3.amazonaws.com list... done
:::   Status: Success (OK)
:::   List updated, transport successful!
::: Getting s3.amazonaws.com list... done
:::   Status: Success (OK)
:::   List updated, transport successful!
::: Getting hosts-file.net list... done
:::   Status: Success (OK)
:::   List updated, transport successful!
::: 
::: Aggregating list of domains... done!
::: Formatting list of domains to remove comments.... done!
::: 130502 domains being pulled in by gravity...
::: Removing duplicate domains.... done!
::: 107265 unique domains trapped in the event horizon.
:::
::: Adding adlist sources to the whitelist... done!
rm: can't remove '/etc/pihole/local.list': No such file or directory
::: Whitelisting 6 domains... done!
::: Nothing to blacklist!
::: No wildcards used!
::: Formatting domains into a HOSTS file...::: Nothing to blacklist!
 done!
:::
::: Cleaning up un-needed files... done!
:::
::: Refresh lists in dnsmasq...s6 service not found for dnsmasq, exiting...
 done!
::: DNS service is running
::: Pi-hole blocking is Enabled
[cont-init.d] 20-start.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting dnsmasq
Starting crond
Starting pihole-FTL
Starting nginx
Starting php-fpm
[services.d] done.
dnsmasq: started, version 2.78 cachesize 10000
dnsmasq: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
dnsmasq: using nameserver 8.8.4.4#53
dnsmasq: using nameserver 8.8.8.8#53
dnsmasq: read /etc/hosts - 7 addresses
dnsmasq: failed to load names from /etc/pihole/black.list: No such file or directory
dnsmasq: read /etc/pihole/local.list - 2 addresses
dnsmasq: read /etc/pihole/gravity.list - 107265 addresses
````

**Comment by EgoAleSum** [comment]
Update on this: I've tried the very same commands on another box, which runs Fedora, and pi-hole works fine there, including FTL.

So, I guess it is because I'm running Alpine as Docker host... I am not sure why this would happen, as Docker motto is "Build, Ship, and Run Any App, Anywhere"... Maybe Alpine has a "bug" in the kernel?

While I'd say you're welcome to test this yourself and maybe fix it somehow, sounds like this is more of an issue on my end, for using Alpine here. I will see if I can switch Linux distro for my "ship" server (my Docker container host).

**Comment by diginc** [comment]
As far as I can tell [alpine's docker package](https://pkgs.alpinelinux.org/packages?name=docker&branch=&repo=&arch=&maintainer=) ([2](https://github.com/ncopa/docker-alpine)) is not an official one but an alpine community maintained package - I'm not sure it's fair to give it too hard of a time for not having 100% feature parity compared to the [official installations](https://docs.docker.com/engine/installation/#server)

Maybe the docker alpine maintainer @ncopa would be interested in the inter-service network communication issue we're seeing here or could shed some light on the issue.  To summarize:  bash/netcat has no problem connecting to a service inside a container but PHP in the same container seems to not be able to...why this works in an official docker install and not in docker's is perplexing.  I am using S6-overlay in my image, not sure if that would have anything to do with it.

**Comment by aurcioli-handy** [comment]
I have a rather hacky solution for this issue but it seems to work just fine. It involves replacing the `pidof` command in the container with a script that just echos back '1'...

pidof
```bash
#!/bin/bash
echo '1'
```

Dockerfile
```
FROM diginc/pi-hole:latest

ADD pidof /bin/pidof
```

Then build and use this image in place of diginc/pi-hole:latest in the `docker_run.sh` file.
