### ISSUE TITLE
Access docker-pi-hole from docker-openvpn

### ISSUE THREAD

**Issue by teresaejunior** [diginc/docker-pi-hole#190]
I assume that many people who setup Pi-hole with Docker also setup OpenVPN with Docker, that is why I'm asking this question here.

I did my setup with the containers *diginc/docker-pi-hole* and *kylemanna/docker-openvpn* in a remote server. The following works:

* Pi-hole works from my laptop (I know I shouldn't open a DNS server to the world, but I did for some time just for testing);
* Pi-hole works from the OpenVPN container (I can use wget with `docker run --dns 172.17.0.3`, and `dig @172.17.0.3 example.com` works);
* OpenVPN works OK with with Google DNS.

What doesn't work is `push "dhcp-option DNS 172.17.0.3"`. I have tried so much random stuff from the web, but no matter what I do, I can't get the OpenVPN process inside the container to access Pi-hole, although other processes can?

Some things I have tried:

* Starting dockerd with `--dns-opt="use-vc"`
* Using `push "route 172.17.0.0 255.255.255.0"` in /etc/openvpn/openvpn.conf
* Using the following in the .ovpn file:
```
script-security 2
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf
```

I am really lost now... Any ideas?

Thank you in advance!

**Comment by thiesschneider** [comment]
Hi,

I wrote a script for this. It is always starting before teh VPN container starts. It is necessary to expose the openvpn.conf.

```
#!/bin/bash
IP_PIHOLE=$(docker inspect -f '{{.NetworkSettings.IPAddress}}' pihole_container)
sed -i -e 's/"dhcp-option DNS .*"/"dhcp-option DNS '$IP_PIHOLE'"/g' /path/to/config/on/host/openvpn.conf
```

hope this works for you!

**Comment by teresaejunior** [comment]
An answer so fast, thank you!

I actually have already placed `push "dhcp-option DNS 172.17.0.3"` in openvpn.conf (your script results `IP_PIHOLE=172.17.0.3` too), but for the life of me I can't figure out why this still doesn't work. There is just no DNS resolution from the OpenVPN server when I do this, although I can ping successfully the Pi-hole container from the OpenVPN container.

Is your VPN server in a container too?

**Comment by teresaejunior** [comment]
I have tried using the IP address with `-p` as shown in https://github.com/diginc/docker-pi-hole/issues/78#issue-196821346, but then I get:

    docker: Error response from daemon: driver failed programming external connectivity
    on endpoint pihole (894baaaada3651aefbb442c6ec99d1528bed89da5251ca42cecbb6e147a42b14
    ): Error starting userland proxy: listen tcp 172.17.0.3:80: bind: cannot assign
    requested address.

**Comment by diginc** [comment]
Have you tried `-e DNSMASQ_LISTENING=all` ?

**Comment by thiesschneider** [comment]
yes. If your container restarts the IP can change. So I replace this file.
I also added `push "redirect-gateway def1 bypass-dhcp"` into the config file.

**Comment by teresaejunior** [comment]
I tried both, but unfortunately, neither works. I'm beginning to suspect UFW may be interfering with Docker iptables rules..., but I have to be careful while disabling it to avoid getting locked out of SSH.

**Comment by thiesschneider** [comment]
can you paste your openvpn config file?
do you have the route option also enabled: `route 192.168.254.0 255.255.255.0`

**Comment by teresaejunior** [comment]
OMG, I got it working with `push "route 172.17.0.0 255.255.255.0"` at the bottom of *openvpn.conf*, which I had previously tried, but probably didn't work because I was testing so much stuff it became messy.

Ads are blocked, but still the following happens (the same behaviour I had noticed by connecting to Pi-hole without OpenVPN):

1) Pages with ads keep loading indefinitely until I hit Escape;
2) A gap is left where the ads were (for example, there is a big white space at the top of youtube.com).

**Comment by teresaejunior** [comment]
Thanks a lot for the help to both of you!

**Comment by diginc** [comment]
Glad you got it figured out.  At some point I'll add documentation explaining how to setup a connected VPN container with docker-compose.  Keep a look out, feel free to comment if you have suggestions.

**Comment by teresaejunior** [comment]
Great! My suggestion would be warning users that `-p 53:53/tcp -p 53:53/udp -p 80:80` will expose the DNS server to the world. Assigning them the `127.0.0.1` IP works (at least for me), while exposing it only locally: `-p 127.0.0.1:53:53/tcp -p 127.0.0.1:53:53/udp -p 127.0.0.1:80:80`.

**Comment by Happyfeet01** [comment]
@teresaejunior can you explain what you have do for your setup? I would using pihole and openvpn.

I have added in the openvpn.config the Route command, but no connection possible. Die

**Comment by teresaejunior** [comment]
I have followed the instructions [from here](https://github.com/prabaprakash/Youtube_Channel/blob/master/OpenVPN%2BPihole.txt) and added a few things of my own. But basically, you'll need also to add the `route` option while editing */etc/openvpn/openvpn.conf* with `nano`, and all `push` options have to be quoted, like `push "dhcp-option DNS 172.17.0.3"` instead of `push dhcp-option DNS 172.17.0.3`.

**Comment by Happyfeet01** [comment]
@teresaejunior I added few things from your link also and the add the push route option but no access to pihole from openvpn. The von connection works fine, also pihole.

**Comment by Happyfeet01** [comment]
Okay, it works. Wrong settings in the Android vpn Client.

**Comment by christofkac** [comment]
I hope somebody monitors this thread.
I have installed pihole/pihole and kylemanna/openvpn on my Synology DS218+ and everything works fine.
For whatever reason, my PiHole container does not have an IP address (docker inspect command returns an empty string) although my OpenVpn container has a proper address 172.17.0.2 - so the command is ok.
As I have no PiHole address, I can't tell OpenVpn to route to Pihole.

Any idea?
Thanks
