### ISSUE TITLE
ARM Update to the newest version

### ISSUE THREAD

**Issue by nsbionix** [diginc/docker-pi-hole#195]
Quick question, when will the new update (3.2) for ARM come out? Got some problems with the old version, that my webinterface is not refreshing and not showing graphs, also blocked sites look different from what i saw on my friends pi. 
![pihole-git1](https://user-images.githubusercontent.com/34452207/33840347-ef05334e-de94-11e7-838e-ec1b9eaf6751.PNG)
![pihole-git2](https://user-images.githubusercontent.com/34452207/33840348-ef1f7060-de94-11e7-85ce-d4bde5de55a9.PNG)

**Comment by diginc** [comment]
The arm tags on `diginc/pi-hole` are deprecated and will be deleted before long.  I'm still in beta for the new multiarch images (based on the docker images of `multiarch` docker organization).  I've already manually pushed the debian arm images to here:   https://hub.docker.com/r/diginc/pi-hole-multiarch/tags/

**Comment by diginc** [comment]
If you have an issues please report them to the new thread I just put up #196
