### ISSUE TITLE
Version 3.2 update MEGATHREAD

### ISSUE THREAD

**Issue by diginc** [diginc/docker-pi-hole#196]
# Known Issues
- The startup may get stuck trying to find DNS unless you set your `docker run --dns 127.0.0.1 --dns 8.8.8.8`.
- I had to remove my persistent data volumes of 3.1 data to get graphs working, maybe an issue with that.

Currently information is scattered in pull requests, old issues, and newer closed issues.  Here's all the info on the update so far:

Current statuses of the different images and their known issues:
## Debian is built and looks operational, but not released
- Point your docker run at `diginc/pi-hole:debian_dev` tag to beta test 3.2, report issues here.
- The [new arm images](https://hub.docker.com/r/diginc/pi-hole-multiarch/tags/) are available on `diginc/pi-hole-multiarch:debian_armhf`
- Pull request(s): #191 

## Alpine needs some work still
- ~~Pull request(s): #192 contains ongoing work for anyone interested in collaborating~~
- Alpine has been removed due to added work time to cut new releases

Keep an eye on https://hub.docker.com/r/diginc/pi-hole/tags/ and the above pull requests for progress

Report all issues / bugs here, no need to open a new issue.

**Comment by diginc** [comment]
Just throwing it out there but I'm having thoughts about making the default 'latest' image tag debian since it is usually much easier to upgrade then alpine.

**Comment by nsbionix** [comment]
So I pulled the 3.2 version with the following script:
`#!/bin/bash
IP_LOOKUP="$(ip route get 8.8.8.8 | awk '{ print $NF; exit }')"
IPv6_LOOKUP="$(ip -6 route get 2001:4860:4860::8888 | awk '{ print $10; exit }')"
IP="${IP:-$IP_LOOKUP}" # use $IP, if set, otherwise IP_LOOKUP
IPv6="${IPv6:-$IPv6_LOOKUP}" # use $IPv6, if set, otherwise IP_LOOKUP
DOCKER_CONFIGS="$(pwd)" # Default of directory you run this from, update to where ever.

echo "IP: ${IP} - IPv6: ${IPv6}"

docker run -d \
 --name pihole \
 -p 53:53/tcp -p 53:53/udp -p 80:80 \
 --dns 127.0.0.1 \
 --dns 8.8.8.8 \
 -v "${DOCKER_CONFIGS}/pihole/:/etc/pihole/" \
 -v "${DOCKER_CONFIGS}/dnsmasq.d/:/etc/dnsmasq.d/" \
 -e ServerIP="${IP}" \
 -e ServerIPv6="${IPv6}" \
 --restart=always \
 diginc/pi-hole-multiarch:v3.2_debian_armhf`

Problems for me are the following:
![pihole-git1](https://user-images.githubusercontent.com/34452207/33844371-6ef67c88-dea0-11e7-9576-ecfee68bd74c.PNG)
![pihole-git2](https://user-images.githubusercontent.com/34452207/33844372-6f125ffc-dea0-11e7-9edb-63fb96625fbc.PNG)
![pihole-git3](https://user-images.githubusercontent.com/34452207/33844373-6f2974f8-dea0-11e7-88d9-d2925be14687.PNG)
![pihole-git4](https://user-images.githubusercontent.com/34452207/33844374-6f401f8c-dea0-11e7-841b-a7a8025a496e.PNG)

**Comment by diginc** [comment]
Are you using fresh volume data or your old 3.1 data?

**Comment by nsbionix** [comment]
I deleted and used prune on every container, image and volume. After that I looked into container/image/volume with ls and everything was clear of data. Then I used the script and got the above results.

**Comment by diginc** [comment]
Can you post `docker logs pihole` to a https://gist.github.com (so it doesn't take up a lot of space in the thread) ?

**Comment by nsbionix** [comment]
https://gist.github.com/nsbionix/84f2941f1b9117ddf30b7c9aff294231

**Comment by diginc** [comment]
Looks like startup broke mid run:

```
ERROR: ServerIPv6 Environment variable (-101) doesn't appear to be a valid IPv6 address
TIP: If your server is not IPv6 enabled just remove '-e ServerIPv6' from your docker container
```

so the rest of the provisioning didn't run - however it didn't end the containers life after that error.  Related PR that may resolve: #194 (no built images for this yet)

For now you can remove the IPv6 variable from the script or docker run command

**Comment by nsbionix** [comment]
I deleted the IPv6 entry and ran into a new problem when I want to fetch the new lists:

![pihole-git5](https://user-images.githubusercontent.com/34452207/33850213-6d3ba9d2-deb3-11e7-9408-85145514f62d.PNG)

**Comment by klud1** [comment]
About Docker-multiarch image...what about using [estesp/manifest-tool](https://github.com/estesp/manifest-tool) in order to ease the pulling process? just running `docker pull dicing/docker-pi-hole:debian` and `docker pull dicing/docker-pi-hole:alpine` and docker will pull the image according to the architecture, either for arm or amd64.

**Comment by diginc** [comment]
@klud1 That topic is more suited to #177 I will reply to your comment there.

**Comment by diginc** [comment]
@nsbionix could you try removing --dns 127.0.0.1 as the primary DNS and move it to secondary?

```
--dns 8.8.8.8 \
--dns 127.0.0.1
```

**Comment by nsbionix** [comment]
rebuild the whole thing but did not work, still getting the message DNS resolution is currently unavailable

**Comment by Anuskuss** [comment]
> @diginc: Just throwing this out there, I'm having thoughts about making the a change to the default `latest` image tag and point to `debian` since it is usually much easier to upgrade then `alpine`.

What even the point in the alpine build? We bother maintaining two seperate builds which basically accomplish the same?

**Comment by diginc** [comment]
Image size is much smaller (100MB) for alpine.  This isn't an issue for
most modern internet connections I know, but it is nice having lean and
mean docker images in general.

It is also an experiment is testing pi-hole compatibility with gcc-musl
that lots of routers run and NGINX webserver instead of lighttpd.  Alpine
is my goto base OS for docker and nginx is my go to webserver in general,
so it's partially my preferences.

RaspberryPi hardware takes significantly longer to download/unpack on then
a proper x86 docker server too so there is that benefit from the size
reduction to consider.

**Comment by Anuskuss** [comment]
I see you. I guess you can decide on your own, but personally I wouldn't "waste" my time with this niche case (some programs don't even have an AMD64 build because they don't want to maintain two projects).

**Comment by unixfox** [comment]
It's working fine for me with the branch `debian_dev`.
@diginc Can you update the development branch to the lastest version of pihole?

**Comment by klud1** [comment]
Point is...some of us might have a "good" internet connection, still there are other that don't.

**Comment by middleagedman** [comment]
I'd love to have the 3.3 version of pihole on debian.  Do the easiest image first, since they build that on debian, then alpine secondary imho.

**Comment by diginc** [comment]
I've axed alpine for now, at this point I don't have the time to maintain it's differences from debian so away it goes.  I've pushed a branch `last_alpine_commits` with the last commit before I started removing all the alpine references.

**Comment by middleagedman** [comment]
Thanks for all your work, we all really appreciate using your free time to do this.  No need to make it a burden for yourself.  :)

**Comment by rix1337** [comment]
@diginc perfectly reasonable decision. I ran into alpine-specific issues on my images as well. Keep it up! Pi-Hole in docker is my backup-dns if my pi-hole dies.. and it works flawlessly

**Comment by diginc** [comment]
debian released to latest tag.  I may go and actually cleanup / delete the alpine tag from docker's tag listing to prevent future confusion too.

**Comment by basrieter** [comment]
What images are best to use now for rPi3?

https://hub.docker.com/r/diginc/pi-hole-multiarch/tags/
-or-
https://hub.docker.com/r/diginc/pi-hole/tags/

**Comment by diginc** [comment]
I pushed a slightly older version of debian to https://hub.docker.com/r/diginc/pi-hole-multiarch/tags/ last night, pushing the latest (3.2.1) version right now.

**Comment by basrieter** [comment]
So we could use either source?

**Comment by diginc** [comment]
I deleted `arm` tag off of `pi-hole` repository since that is an old old version.

https://hub.docker.com/r/diginc/pi-hole-multiarch/tags/ is the latest, greatest.  I just need to add it to the README and finish up the automated travis-ci build for it so I can stop running docker pushes from my development environment.

**Comment by middleagedman** [comment]
Just FYI.. I pulled down your pi-hole:latest, and it doesn't start up.. hangs around

Using custom DNS servers: 208.67.222.222 & 208.67.220.220
DNSMasq binding to default interface: eth0
Added ENV to php:
                        "PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
                        "ServerIP" => "192.168.1.3",
                        "VIRTUAL_HOST" => "192.168.1.3",
Using IPv4
dnsmasq: syntax check OK.
::: Testing DNSmasq config: ::: Testing lighttpd config: Syntax OK
::: All config checks passed, starting ...
::: Docker start setup complete
  [✗] DNS resolution is currently unavailable


Looks like this guy never finishes
foreground  /var/run/s6/etc/cont-init.d/20-start.sh  importas -u ? ? if  s6-echo  --  [cont-init.d] 20-start.sh: exited ${?}.  ifelse  s6-test  2  -eq  0   exit  0  exit ${?}

**Comment by middleagedman** [comment]
FYI.. I'm seeing issues if /etc/resolv.conf doesn't have "nameserver 127.0.0.1" in it as the first entry.  I tried passing it via the DNS1= option but it looks like that does nothing and it still grabs from dhcpcd

Using custom DNS servers: 127.0.0.1 & 8.8.4.4
DNSMasq binding to default interface: eth0
Added ENV to php:
                        "PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
                        "ServerIP" => "192.168.1.3",
                        "VIRTUAL_HOST" => "192.168.1.3",
Using IPv4
dnsmasq: syntax check OK.
::: Testing DNSmasq config: ::: Testing lighttpd config: Syntax OK
::: All config checks passed, starting ...
::: Docker start setup complete
  [✗] DNS resolution is currently unavailable

 more /etc/resolv.conf
# Generated by dhcpcd from enp5s0.dhcp
nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 192.168.1.3
nameserver 208.67.220.220
# /etc/resolv.conf.tail can replace this line

**Comment by middleagedman** [comment]
Found the solution.. Looks like it's fixed in this commit
https://github.com/pi-hole/pi-hole/pull/1856/commits/1078aa499c26ba0b3dfb886c7a1a6f3d95d00591

I updated my gravity.sh file instead of the container and it starts properly now.

**Comment by diginc** [comment]
Good find, I think I was working around this by just setting a dns server in the docker run command as the known issue said: 

> Known Issues
> - The startup may get stuck trying to find DNS unless you set your docker run --dns 127.0.0.1 --dns 8.8.8.8.
> - I had to remove my persistent data volumes of 3.1 data to get graphs working, maybe an issue with that.

Manually patching that maybe a better solution.

**Comment by diginc** [comment]
Re-opening for visibility on the --dns 127.0.0.1 workaround (for now)

**Comment by middleagedman** [comment]
Yea.. I just overwrote gravity.sh with the 3.2.1 file and graphs are working, boot is working. I still get N/A on the version check, but I'm still debugging that.

**Comment by middleagedman** [comment]
Nm.. the version isn't populated until the cron.d pihole job runs daily.

**Comment by DL6ER** [comment]
> Nm.. the version isn't populated until the cron.d pihole job runs daily.

Yeah, I admit to have forgotten this. You can manually run
```
pihole updatechecker remote
```

This is fixed in the core code by https://github.com/pi-hole/pi-hole/pull/1878

**Comment by diginc** [comment]
#211 deployed a new dev tag that has the latest development branch code for the next release on it...and maybe any bugs on dev also :)

I believe it removes the need for `--dns 127.0.0.1` - I haven't tested it extensively but my docker-compose came up cleanly without it.
