### ISSUE TITLE
Try on actual pi hardware

### ISSUE THREAD

**Issue by diginc** [diginc/docker-pi-hole#2]
At some point I'd like to spike swapping out the base `FROM` x86 images with ARM versions and building/running with [hyperiot](http://blog.hypriot.com/getting-started-with-docker-on-your-arm-device/).   A little googling revealed both debian(raspian) and alpine have arm images available.

**Comment by RnbWd** [comment]
hey I'm about  to test this on hypriot and docker for mac (which lets me run arm and other architectures locally). I actually just tested out the main pinhole (not docker) within the newest hypriotOS 8.0 - and it worked. Initially there was conflict on port 53 using docker containers, so I uninstalled pinhole - which uninstalled dnsmasq and i think that port is open now, so I'll give it another go. Assume its the package named `alpine_pi-2.6.3` and `docker_pi-2.6.3`?

**Comment by diginc** [comment]
Awesome!  For anyone else wondering about the docker tags, I maintain the default `:latest` tag as an alias for `:alpine`, while :debian is separate and you have to pull it specifically.  I also make a separate tag for each specific version so that old versions survive the test of time.

So currently alpine/latest is also tagged `alpine_pi-2.6.3_admin-1.2` which deprecated the previous version of `alpine_pi-2.6.2_admin-1.2`.  `debian` and `debian_pi-2.6.3_admin-1.2` are currently the same, etc so on and so forth.  There were a couple older releases that I didn't keep the tags for.

You shouldn't need to specify the version tags unless you want to pin your version or need an old version.

**Comment by RnbWd** [comment]
I still can't get the ports to work correctly because something is listening on port 53... i'm very familiar with jwilder's repo but haven't ran it on a pi yet - also still getting used to hypriot's new image which is only a day old.

**Comment by diginc** [comment]
Jwilder will help you solve any port 80 conflicts but I'm not sure what would be using 53 on mac.  try `netstat -ap | grep 53` and see if that tells you?

**Comment by RnbWd** [comment]
oh i'm messing everything up - destabilized the docker client on the raspi completely, and docker for mac is throwing completely different errors for different reasons, but it runs on hypriot's image without docker so I'm sure there's a way to encapsulate it.

**Comment by Fedora-Core** [comment]
Concerning IP-Ports conflicts =>

**The Linux kernel - Great Stuff !**

"In Linux 2.2 an interface can carry multiple IP addresses,
this replaces the alias device concept in 2.0"

° Linux 2.0 was published in 1996, June 9.
° Linux 2.2 was published in 1999, January 25.

**This would be a great idea for the Docker-Host !**

° Place the Pi-hole DNS server in his own Docker Container,
 with his own Docker Host IP address "x.y.z.21" on IP port 53.
° Place the Pi-hole WEB server in his own Docker Container,
 with his own Docker Host IP address "x.y.z.22" on IP port 80.
° etc...

A Sample Network Interfaces Config,
with comments for a Raspbian Jessie (Debian 8 based),
can be found here =>

[https://github.com/Fedora-Core/Pi-hole-adblock-multiple-IP-addresses](https://github.com/Fedora-Core/Pi-hole-adblock-multiple-IP-addresses)

**Comment by Fedora-Core** [comment]
_Background Information =>_

From:
publisher: Packt
title: Learning Docker
page: 102 =>

_=== Start of Quote ===_

**Binding a container to a specific IP address**


Until now, with the method that we have learnt, the containers always get bound to
all the IP addresses configured in the Docker host. However, you may want to offer
different services on different IP addresses. In other words, a specific IP address and
port would be configured to offer a particular service. We can achieve this in Docker
using the **-p <ip>:<hostPort>:<containerPort>** option of the **docker run**
subcommand, as shown in the following example:

**$ sudo docker run -d -p 198.51.100.73:80:80 apache2**

**92f107537bebd48e8917ea4f4788bf3f57064c8c996fc23ea0fd8ea49b4f3335**

Here, the IP address must be a valid IP address on the Docker host. If the specified
IP address is not a valid IP address on the Docker host, the container launch will fail
with an error message, as follows:

**2014/11/09 10:22:10 Error response from daemon: Cannot start container**

**99db8d30b284c0a0826d68044c42c370875d2c3cad0b87001b858ba78e9de53b:**

**Error starting userland proxy: listen tcp 198.51.100.73:80: bind:**

**cannot assign requested address**


Now, let's quickly review the port mapping as well as the NAT entry for the
preceding example.
The following text is an excerpt from the output of the **docker ps** subcommand
that shows the details of this container:

**92f107537beb apache2:latest "/usr/sbin/apache2ct About**

**a minute ago Up About a minute 198.51.100.73:80->80/tcp**

**boring_ptolemy**


The following text is an excerpt from the output of the **iptables -n nat -L -n**
command that shows the DNAT entry created for this container:

**DNAT tcp -- 0.0.0.0/0 198.51.100.73 tcp dpt:80**

**to:172.17.0.15:80**


After reviewing both the output of the docker run subcommand and the DNAT
entry of iptables, you will realize how elegantly the Docker engine has configured
the service offered by the container on the IP address 198.51.100.73 and port 80 of
the Docker host.

_===  End of Quote ===_


Greetings, F.C.

**Comment by diginc** [comment]
Cool suggestion.  Another similar solution I was eyeballing was setting up a docker bridge to allow the container to directly pull DHCP like a bridged VM would.  I've read the docs but have not tried it yet.  Bridging may prevent having to worry about host based services listening on all interfaces and conflicting with docker ports on next reboot.

All solutions to port conflicts have pitfalls for users...it kind of just depends how technically savvy the docker user is.  It'd probably be worth documenting the various possible solutions in the wiki or readme though.

Thanks for the feedback.

**Comment by Symbiot78** [comment]
dammit... I really wanna get this to work but am facing the "my webserver is already using port 80".. so I need the reverse-proxy thing..
but I think I'm in over my head... I don't know how to set it up.. I pulled jwilders container but not really sure what to do ...

**Comment by Symbiot78** [comment]
I guess I could change the webserver host Port but I'd much much rather learn the other stuff...

**Comment by RnbWd** [comment]
I was about to write a long write up suggesting npm libraries like 

- https://github.com/typicode/hotel

- https://github.com/mafintosh/discovery-swarm

- https://github.com/mafintosh/dnsjack

- https://github.com/mafintosh/docker-remote-api

- https://github.com/mafintosh/multicast-dns

But then I remembered that I've been using docker beta for months and just for used to it mapping onto port 80 trivially. If it works on Mac - it cam totally work on a pi. Unfortunately I don't know the answer, but I'd still recommend checking out mafintosh's docker / node / networking hacks (torrenting containers because of network speed where he lives, putting docker inside of browsers, creating local mesh / dns networks and mapping them the ip addresses , hyperdrive fs - off topic but he's written some cool stuff

**Comment by RnbWd** [comment]
I'd actually recommend openwrt's wiki

**Comment by diginc** [comment]
#28 and #30 helped close this, we have manual building possible now.

#35 will set up automated building for this.
