### ISSUE TITLE
Docker diginc/pi-hole:alpine tag not working?

### ISSUE THREAD

**Issue by poldim** [diginc/docker-pi-hole#206]
I'm trying to do an update on my docker compose and get the following error:

>     docker-compose pull pihole
>     Pulling pihole (diginc/pi-hole:alpine)...
>     ERROR: manifest for diginc/pi-hole:alpine not found

It also looks like it's missing from the v3.2 update but is available for v3.1.4 which is what I currently have: https://hub.docker.com/r/diginc/pi-hole/tags/

Am I missing something?

**Comment by diginc** [comment]
I dropped Alpine support for 3.2.  I didn't have time to update it.  Please
use lastest or Debian tag, it should work great

**Comment by poldim** [comment]
Booted up on debian, no issues!  Thanks!
