### ISSUE TITLE
Image diginc/pi-hole:arm not working anymore

### ISSUE THREAD

**Issue by stackErr-NameNotResolved** [diginc/docker-pi-hole#207]
Running with the tag arm results in the following pull: ERROR: manifest for diginc/pi-hole:arm not found

**Comment by diginc** [comment]
Give [diginc/pi-hole-multiarch](https://hub.docker.com/r/diginc/pi-hole-multiarch/tags/) a shot

I deprecated the `arm` build on `pi-hole` and moved it to `pi-hole-multiarch` because of an change in the base image that didn't allow it to be automatically built on docker cloud.

**Comment by oscarnyl** [comment]
I created a PR to document this: https://github.com/diginc/docker-pi-hole/pull/209
