### ISSUE TITLE
(mod_fastcgi.c.1406) [ERROR]: spawning fcgi failed

### ISSUE THREAD

**Issue by xenithorb** [diginc/docker-pi-hole#217]
```
2018-01-13 13:52:17: (log.c.164) server started
2018-01-13 13:52:17: (mod_fastcgi.c.984) bind failed for: unix:/var/run/lighttpd/php.socket-0 No such file or directory
2018-01-13 13:52:17: (mod_fastcgi.c.1406) [ERROR]: spawning fcgi failed.
2018-01-13 13:52:17: (server.c.1022) Configuration of plugins failed. Going down.
```

Getting this in /var/log/lighthttpd/error.log 

`docker logs` shows s6 is restarting lighthttpd over and over again, but otherwise pi-hole setup was successful and DNSmasq is running and working. FTL is also running OK. 

```
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
docker.io/diginc/pi-hole   latest              6b77d5329fd4        8 days ago          330.5 MB

**Comment by diginc** [comment]
Are there any volumes pointed to /var/?  What's the container run configuration look like?

**Comment by vmtyler** [comment]
+1 on this issue. should we put a PR in for the temp fix?

**Comment by diginc** [comment]
I've been out sick for a week, trying to reproduce with docker_run.sh now.

**Comment by diginc** [comment]
I was unable to reproduce.  Can I see a docker run command example?  Also what OS & Docker version are those of you seeing this problem using?

I ran this exactly: https://raw.githubusercontent.com/diginc/docker-pi-hole/master/docker_run.sh

```
$ docker inspect pihole | grep -i image
        "Image": "sha256:6b77d5329fd484527ec719e52e3f2c85cecea0a06a652feeed8779f458d8abd0",
            "Image": "diginc/pi-hole:latest",
                "image": "diginc/pi-hole:debian_amd64",
```

/var/run/lighttpd permissions:

```
$ docker exec pihole ls -lat /var/run/lighttpd
total 8
drwxr-xr-x 2 www-data www-data 4096 Jan 25 15:17 .
drwxr-xr-x 8 root     root     4096 Jan 25 15:17 ..
srwxr-xr-x 1 www-data www-data    0 Jan 25 15:17 php.socket-0
```

**Comment by vmtyler** [comment]
```
docker inspect pihole | grep -i image
        "Image": "sha256:6b77d5329fd484527ec719e52e3f2c85cecea0a06a652feeed8779f458d8abd0",
            "Image": "diginc/pi-hole",
                "image": "diginc/pi-hole:debian_amd64",
```
and here:
```
docker exec pihole ls -lat /var/run/lighttpd
ls: cannot access /var/run/lighttpd: No such file or directory```

**Comment by vmtyler** [comment]
whoops almost forgot the docker run:
```
/usr/bin/docker run --rm \
--name pihole \
--dns 127.0.0.1 --dns 8.8.8.8 \
-p 53:53/tcp -p 53:53/udp -p 80:80 \
-v "/var/opt/pihole/pihole/:/etc/pihole/" \
-v "/var/opt/pihole/dnsmasq.d/:/etc/dnsmasq.d/" \
-e ServerIP= ********** \
-e WEBPASSWORD= ******** \
-e VIRTUAL_HOST=********* \
diginc/pi-hole
```

**Comment by diginc** [comment]
what about `docker exec pihole ls -lat /var/run/`

#220 reports this issue happening on CentOS and you report Fedora.  Since I'm unable to reproduce the problem on ubuntu I'm wondering if there's a connection between this bug and the Docker OS being RedHat based.  @xenithorb what OS are you?

If the work around is simply a `mkdir /var/run/lighttpd` in install.sh I'm ok with that adding that...but I'm very curious what the cause is still.

**Comment by vmtyler** [comment]
Interesting.
Here:
```
docker exec pihole ls -lat /var/run/
total 28
-rw-r--r-- 1 root root    4 Jan 25 17:38 lighttpd.pid
drwxr-xr-x 5 root root  220 Jan 25 17:38 .
-rw-r--r-- 1 root root    4 Jan 25 17:38 pihole-FTL.port
---------- 1 root root    0 Jan 25 17:38 crond.reboot
-rw-r--r-- 1 root root    3 Jan 25 17:38 pihole-FTL.pid
-rw-r--r-- 1 root root    4 Jan 25 17:38 crond.pid
-rw-r--r-- 1 root root    4 Jan 25 17:38 dnsmasq.pid
drwxr-xr-x 1 root root 4096 Jan 25 17:38 ..
drwxr-xr-x 7 root root  140 Jan 25 17:38 s6
drwxr-xr-x 2 root root   40 Jan 25 17:38 lock
drwxr-xr-x 3 root root 4096 Jan 25 17:38 secrets
```
so much for the host OS not being that important to container images..

**Comment by xenithorb** [comment]
CentOS 7.4 here @diginc

**Comment by diginc** [comment]
https://github.com/just-containers/s6-overlay/issues/158#issuecomment-228586101 maybe the cause or related?

**Comment by vmtyler** [comment]
Yeah looks like it- I think the best workaround for now is to add the VOLUME /run to the dockerfile or just make a note for people to add -v /run to the docker run command.

Thoughts?

**Comment by diginc** [comment]
I took away that renaming /init to something different would also be a valid work around since it would prevent the auto mounting /var.

**Comment by diginc** [comment]
debian_dev tag use /s6-init instead of /init now: https://hub.docker.com/r/diginc/pi-hole/tags/

**Comment by xenithorb** [comment]
I can report that both solutions work, mounting `-v /run` and also the renaming of `/init` 

Thanks
