### ISSUE TITLE
New docker build - no WebGUI

### ISSUE THREAD

**Issue by AHrubik** [diginc/docker-pi-hole#228]
|# docker images
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
docker.io/diginc/pi-hole   latest              6b77d5329fd4        4 weeks ago         330.5 MB
docker.io/diginc/pi-hole   <none>              f9163db108ed        8 months ago        143.7 MB

docker run -d --name piholeB -p 53:53/tcp -p 53:53/udp -p 80:80 -e ServerIP=192.168.1.2 -e VIRTUAL_HOST=192.168.1.2 --restart=unless-stopped diginc/pi-hole:latest

|# docker ps
CONTAINER ID        IMAGE                   COMMAND             CREATED             STATUS              PORTS                                                        NAMES
0a4b05ee07d0        diginc/pi-hole:latest   "/init"             16 minutes ago      Up 6 minutes        0.0.0.0:53->53/tcp, 0.0.0.0:80->80/tcp, 0.0.0.0:53->53/udp   piholeB

No WebGUI
DNS resolution works
lighttpd won't start

Sample log output
```
Starting lighttpd
dnsmasq: query[A] channel.status.request.url from 192.168.1.1
dnsmasq: forwarded channel.status.request.url to 8.8.4.4
dnsmasq: query[AAAA] channel.status.request.url from 192.168.1.1
dnsmasq: forwarded channel.status.request.url to 8.8.4.4
dnsmasq: reply channel.status.request.url is NXDOMAIN
dnsmasq: reply channel.status.request.url is NXDOMAIN
dnsmasq: query[A] channel.status.request.url from 192.168.1.1
dnsmasq: cached channel.status.request.url is NXDOMAIN
dnsmasq: query[AAAA] channel.status.request.url from 192.168.1.1
dnsmasq: cached channel.status.request.url is NXDOMAIN
dnsmasq: query[A] device-metrics-us.amazon.com from 192.168.1.119
dnsmasq: /etc/pihole/gravity.list device-metrics-us.amazon.com is 192.168.1.2
Starting lighttpd
Starting lighttpd
Starting lighttpd
dnsmasq: query[A] device-metrics-us.amazon.com from 192.168.1.119
dnsmasq: /etc/pihole/gravity.list device-metrics-us.amazon.com is 192.168.1.2
dnsmasq: query[A] www.privateinternetaccess.com from 192.168.1.110
dnsmasq: forwarded www.privateinternetaccess.com to 8.8.4.4
dnsmasq: query[A] www.privateinternetaccess.com from 192.168.1.110
dnsmasq: forwarded www.privateinternetaccess.com to 8.8.8.8
dnsmasq: forwarded www.privateinternetaccess.com to 8.8.4.4
dnsmasq: reply www.privateinternetaccess.com is <CNAME>
dnsmasq: reply privateinternetaccess.com.edgekey.net is <CNAME>
dnsmasq: reply e9476.ksd.akamaiedge.net is 184.84.80.38
Starting lighttpd
Starting lighttpd
dnsmasq: query[A] device-metrics-us.amazon.com from 192.168.1.119
dnsmasq: /etc/pihole/gravity.list device-metrics-us.amazon.com is 192.168.1.2
Starting lighttpd
Starting lighttpd
```

**Comment by olfolfolf** [comment]
I have the same error.

stdout - a lot of:
`Starting lighttpd`

stderr - a lot of:
`Tue Feb 13 23:13:17 2018 (440): Fatal Error Unable to create lock file: Bad file descriptor (9)`

**Comment by tchellomello** [comment]
Hello guys, 
   I had similar issue. What happens if you start the image with -v ~/run:/run ?
   This fixed the issue for me.

**Comment by AHrubik** [comment]
@tchellomello What does that variable do?

**Comment by olfolfolf** [comment]
@tchellomello 
I tried it, the error remains ..

**Comment by markiewb** [comment]
@AHrubik: 
> What does that variable do?

It isn't a variable but a volume mapping.

**Comment by cnu80** [comment]
in the configuration file 
`/etc/lighttpd/conf-enabled/15-fastcgi-php.conf `
is
`/var/run/lighttpd/php.socket `
defined.
But the directory` /var/run/lighttpd` is missing.

error.log from lighthttpd:
(mod_fastcgi.c.984) bind failed for: unix:/var/run/lighttpd/php.socket-0 No such file or directory

**Comment by AHrubik** [comment]
New 3.3 image solved problems.

Thank you for your time and effort.

Closing.
