### ISSUE TITLE
[ERROR]: Unable to parse results from queryads.php: Unhandled error message ()

### ISSUE THREAD

**Issue by tonyklawrence** [diginc/docker-pi-hole#229]
When running the debian image and specifying the environment WEB_PORT to run the lighttpd server on a different port this error occurs when hitting the web root.

I believe the issue is that the index.php file has a hard coded get from http://127.0.0.1 which will fail if the server is running on a different port.

See: https://github.com/pi-hole/pi-hole/blob/e602008459128c233899b1e9d70cca0f38f41670/advanced/index.php#L136

It also refers to http://pi.hole/ which also fails: https://github.com/pi-hole/pi-hole/blob/e602008459128c233899b1e9d70cca0f38f41670/advanced/index.php#L231

**Comment by diginc** [comment]
Forgot to follow up after merging #234 , is this fixed?

**Comment by tonyklawrence** [comment]
Yes, seems to be working well now, thanks!

**Comment by MurkBRA** [comment]
Seems this bug is back on `diginc/pi-hole-multiarch:debian_armhf`
I change the publish to 89:80 and got this error 
[ERROR]: Unable to parse results from queryads.php: Unhandled error message ()
If publish the 80:80 work fine
