### ISSUE TITLE
Inconsistent Behavior with Whitelist from Admin GUI

### ISSUE THREAD

**Issue by dbec** [diginc/docker-pi-hole#23]
Using "debian_dev" tagged version, in the admin interface I'm noticing odd behavior:
Add a domain to whitelist
Confirm domain is added to end of /etc/pihole/whitelist.txt on container
Remove domain from whitelist via red garbage can icon on the right
Domain is removed from list in the GUI
Domain is no longer in whitelist.txt
However, domain is added to end of gravity.list (?!), causing the domain to be "pi-holed"

I noticed this in earlier versions as well.

**Comment by diginc** [comment]
```
root@90dab8d5adbc:/# sudo pihole -w -q issue23.github
::: You are root.
:::
::: Modifying HOSTS file to whitelist 9 domains... done!
:::
::: Refresh lists in dnsmasq... done!
root@90dab8d5adbc:/# grep 'issue23' /etc/pihole/*
/etc/pihole/whitelist.txt:issue23.github

root@90dab8d5adbc:/# sudo pihole -w -q -d issue23.github
::: You are root.
:::
::: Modifying HOSTS file to un-whitelist domains...
:::    Un-whitelisting issue23.github on IPv4 done!
:::        Removing issue23.github from /etc/pihole/whitelist.txt... done!
:::
::: Refresh lists in dnsmasq... done!
root@90dab8d5adbc:/# grep 'issue23' /etc/pihole/*
/etc/pihole/gravity.list:192.168.41.55 issue23.github
```

Yup...I can reproduce this without using my AdminLTE fork code changes so I'm going to have to call in @pi-hole/dashboard , what do you guys think?  

This line to blame?  
https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/whitelist.sh#L185
un-whitelist = auto-blacklist ?

**Comment by diginc** [comment]
@dbec would you like to open a pi-hole main repo issue or shall I?

**Comment by dbec** [comment]
I've opened an issue (#581). Thanks!
