### ISSUE TITLE
Version 3.3

### ISSUE THREAD

**Issue by unixfox** [diginc/docker-pi-hole#231]
Is it possible to update the Docker container to the version 3.3: https://github.com/pi-hole/pi-hole/releases/tag/v3.3?

**Comment by rodalpho** [comment]
Yes, just came here to check that. 3.3 has been out for a week now.

**Comment by diginc** [comment]
I published the debian_dev image tag last night (#233) and have been getting it a once over tonight.  I can't find any major issues in my setup, I think some of the issues with the 3.2 image and pre-release of image dev branches pre-3.3 are resolved.

#235 will release dev to production tags/master after tests are finished and the image builds take another few minutes to deploy after that.

**Comment by unixfox** [comment]
Thank you so much @diginc!
I upgraded from the 3.2 image to the 3.3 image and it's working pretty great.
