### ISSUE TITLE
Extra hosts without docker compose? Is that possible?

### ISSUE THREAD

**Issue by beloso** [diginc/docker-pi-hole#249]
I want to add some of my local IPs to pi-hole.

I have edited `local.list` in my host folder but when I restart the container it gets overwritten.

Is there a way to accomplish this?

**Comment by diginc** [comment]
https://docs.docker.com/engine/reference/run/#managing-etchosts

**Comment by beloso** [comment]
I don't know why, but it didn't work for me.
Anyways, I ended up setting up a docker compose file
