### ISSUE TITLE
Alpine / Nginx Version 403 Forbidden Error

### ISSUE THREAD

**Issue by dbec** [diginc/docker-pi-hole#25]
In the Alpine / Nginx version, instead of the default landing page (blank html) I get a 403 Forbidden error. It will come up fine if I run 'cp /var/www/html/pihole/index.html /var/www/html/' inside the container.

**Comment by dbec** [comment]
Is more information needed? Or is this by design?

**Comment by diginc** [comment]
Sorry, I just haven't had time to get these added and working for both versions.  I've been working on getting this tested to prevent regression too.

**Comment by diginc** [comment]
I ended up tweaking the nginx config a little to match the lighttpd default configuration behavior to fix it.  I probably could have done it in a fraction of the time but I really wanted tests.  The automated test are awesome and will tell me if anything breaks in the future - hopefully saving me lots of time in the long run.
