### ISSUE TITLE
opening errorlog '/var/log/lighttpd/error.log' failed: Permission denied

### ISSUE THREAD

**Issue by tehniemer** [diginc/docker-pi-hole#252]
## Description
PiHole seems to be running and blocking domains, but the WebUI will not start. This has manifested in the last day or so.

## Expected Behavior
Be able to access the WebUI

## Actual Behavior
WebUI does not exist

## Steps to Reproduce and debugging done
Spin up container, watch it fail.

## Debug steps I have tried

- [x ] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ x] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x ] I have searched this repository for existing issues and pull requests that look similar

## Your Environment 
* Docker Host Operating System and OS Version: QNAP QTS 4.3.4
* Docker Version: 17.07.0-ce
* Hardware architecture: x64

Just installed watchtower, not sure if that could cause anything.....log attached.
[pihole_debug-sanitized.log](https://github.com/diginc/docker-pi-hole/files/1878361/pihole_debug-sanitized.log)

**Comment by tehniemer** [comment]
This seems to only be an issue with the ```:latest``` tag. I deployed containers with tags ```:debian_dev``` ```:debian_v3.3``` and ```:debian_v3.2.1``` and I did not get this failure.

**Comment by diginc** [comment]
latest was updated yesterday (based off the dev changes), along with the v3.3.1 update.  make sure you pull it down and it downloads a new version.

It may have just been an issue with your old container or the 'latest' image you had cached locally.

If you're still having issues seeing your `docker run` and first 100 or so lines of `docker logs`, the point at which the webserver is starting, would help diagnose.  I didn't see anything in your debug log that stood, the docker log is generally more helpful for service startup issues.

**Comment by tehniemer** [comment]
Fixed with v3.3.1
