### ISSUE TITLE
Version 3.3.1

### ISSUE THREAD

**Issue by unixfox** [diginc/docker-pi-hole#255]
Is it possible to update the Docker image to the version 3.3.1: https://github.com/pi-hole/pi-hole/releases/tag/v3.3.1?
Thank you.

**Comment by LaurentDumont** [comment]
I saw the PR but it looks like the CI on Docker Cloud broke? Does someone need to manually approve the build process?

**Comment by ksylvan** [comment]
Docker Could builds seem to be out of date, yes. Can we kick them?

**Comment by basrieter** [comment]
How can we get v3.3.1 on armhf? Seems that only 3.3 is available on diginc/pi-hole-multiarch:v3.3_debian_armhf
