### ISSUE TITLE
pihole-FTP started from init.d and supervise

### ISSUE THREAD

**Issue by jamesgol** [diginc/docker-pi-hole#257]
I'm not sure when this started, but it might be related to this commit (https://github.com/pi-hole/pi-hole/commit/8b79017d0f05e84b5eac5ccc44477252c2ad928c), but maybe not.  Not sure if this docker was explicitly removing the init.d in some fashion or what.

This is causing excessive cpu, memory, and storage use while an extra process starts and stops and repeatedly adding log entries to the /var/log/pihole-FTL.log file

I'm not sure if you have a preference to stick with the supervise script or init.d.  I've barely looked at this repo (and pihole) so I'm not sure the best course of action.  On my setup I just manually removed the supervise version of the script.

**Comment by jamesgol** [comment]
Sorry, I'm wrong here.  It doesn't appear to be using the init.d entry anymore, it's just that the env var FTL_CMD isn't making it to the script to keep it from daemonizing.

**Comment by Gh0stR1pp3r** [comment]
Is there a workaround for this in the meantime? Kills my system if i try to run it.

**Comment by diginc** [comment]
add -e FTL_CMD='no-daemon' to your docker run as a work around.

Adding fix now by moving this env to the Dockerfile instead of /start.sh which doesn't seem to be shared with s6's environment.  strange since I thought the debug version of it worked.

**Comment by jamesgol** [comment]
I was just starting to dig into seeing how the env was passed around, and it definitely seems like vars set in start.sh don't make it out.

Briefly looking at https://github.com/just-containers/s6-overlay it looks like possibly setting S6_KEEP_ENV will allow the env to stay but I can't be sure and I'm not sure I want to start down the rabbit hole of figuring it out.

**Comment by diginc** [comment]
The s6 services are children of PID 1 and inherit it's environment.  Putting it in /start.sh was flawed (not sure how it ever worked without setting it at run time) since it doesn't start the services but is actually a child of s6 and once start.sh is done, it exits destroying those environmental changes.  So it's more of a sibling or nephew environment of the services and has no control of services' environments.

To visualize it take a look at the PIDs of start.sh and compare it to a long running container after start.sh

```
UID        PID  PPID  C STIME TTY          TIME CMD
root       209   206  0 17:47 ?        00:00:00               foreground  /var/run/s6/etc/cont-init.d/20-start.sh  importas -u ? ? if  s6-echo  --  [cont-init.d] 20-start.sh: exited ${?}.  ifelse  s6-test  2  -eq  0   exit  0  exit ${?}
root       211   209  0 17:47 ?        00:00:00                 bash /var/run/s6/etc/cont-init.d/20-start.sh
root       216   211  0 17:47 ?        00:00:00                   bash -e /start.sh
```

```
$ docker exec 6b296c5e928b ps -efH
UID        PID  PPID  C STIME TTY          TIME CMD
root      5963     0  0 12:44 ?        00:00:00 ps -efH
root         1     0  0 Mar16 ?        00:00:00 s6-svscan -t0 /var/run/s6/services
root        30     1  0 Mar16 ?        00:00:00   s6-supervise s6-fdholderd
root       736     1  0 Mar16 ?        00:00:00   s6-supervise dnsmasq
root       742   736  0 Mar16 ?        00:00:00     bash ./run
root       754   742  0 Mar16 ?        00:01:08       dnsmasq -7 /etc/dnsmasq.d --no-daemon
root       737     1  0 Mar16 ?        00:00:00   s6-supervise pihole-FTL
root       743   737  0 Mar16 ?        00:00:00     bash ./run
root       760   743  0 Mar16 ?        00:10:57       pihole-FTL debug
root       738     1  0 Mar16 ?        00:00:00   s6-supervise lighttpd
root       744   738  0 Mar16 ?        00:00:00     bash ./run
www-data   755   744  0 Mar16 ?        00:00:54       lighttpd -D -f /etc/lighttpd/lighttpd.conf
www-data   778   755  0 Mar16 ?        00:00:00         /usr/bin/php-cgi
www-data   779   778  0 Mar16 ?        00:00:00           /usr/bin/php-cgi
www-data   780   778  0 Mar16 ?        00:00:00           /usr/bin/php-cgi
www-data   781   778  0 Mar16 ?        00:00:00           /usr/bin/php-cgi
www-data   782   778  0 Mar16 ?        00:00:00           /usr/bin/php-cgi
root       740     1  0 Mar16 ?        00:00:00   s6-supervise cron
root       745   740  0 Mar16 ?        00:00:00     bash ./run
root       761   745  0 Mar16 ?        00:00:02       /usr/sbin/cron -f
```

As shown in my fix here https://github.com/diginc/docker-pi-hole/pull/258 - moving the FTL_CMD env var to the Dockerfile with the default hard coded there still enabled `-e FTL_CMD=debug` overriding but actually is set into PID1's environment and gets picked up by services.
