### ISSUE TITLE
second pihole-FTL process 100% CPU and filling up FS

### ISSUE THREAD

**Issue by 01010101001** [diginc/docker-pi-hole#264]
Hello

I have been running the pihole docker successfully for quite a while on a small ubuntu (stretch/sid) server and find it pretty neat. I am competent with linux but new to docker.  my docker creation command is

IP_LOOKUP="$(ip route get 8.8.8.8 | awk '{ print $NF; exit }')"  
IPv6_LOOKUP="$(ip -6 route get 2001:4860:4860::8888 | awk '{ print $5; exit }')"  # tweaked to make IPv6 work on my box, which it does
IP="${IP:-$IP_LOOKUP}"  
IPv6="${IPv6:-$IPv6_LOOKUP}"  
DOCKER_CONFIGS="/etc/pihole" 
docker run -d \
--name pihole \
-p 53:53/tcp -p 53:53/udp -p 80:80 \
-v "${DOCKER_CONFIGS}/pihole/:/etc/pihole/" \
-v "${DOCKER_CONFIGS}/dnsmasq.d/:/etc/pihole_dnsmasq.d/" \
-e WEBPASSWORD=XXXXXXXX \
-e ServerIP="${IP}" \
-e ServerIPv6="${IPv6}" \
--restart=unless-stopped \
diginc/pi-hole:latest

Recently I noticed that my filesystem is full and pihole's web interface is  non functional (it loads up but can't connect to the API so none of the graphs are populated).
upon investigation, I actually have 2 pihole-FTL processes running at all times, and the second one is hugging 100% CPU. it seems to keep trying to kill the first one.- /var/log/pihole-FTL.log is filling up quick with this:

[2018-04-15 15:52:37.435] 805 - pihole-FTL
[2018-04-15 15:52:37.435] Found pihole-FTL process with PID 805 (my PID 1017) - killing it ...
[2018-04-15 15:52:37.435] 805 - pihole-FTL
[2018-04-15 15:52:37.435] Found pihole-FTL process with PID 805 (my PID 1017) - killing it ...
..

(thousands of these per second). it's not actually killing it though and both keep running.  lsof is full of thousands of /proc entries from the second pihole-FTL process and the max open files limit is reached. 
while all of this happens, dnsmasq is doing its job just fine and I have name resolution working perfectly on my network, even once the file system fills up. 

what I did try so far includes:
- docker rm -f pihole and recreate
- update docker images and delete/recreate
- update images, delete the two persistent mounts, delete & recreate (which should bring me back to square 1 right?)

but no matter what this behaviour continues... as soon as I start a new image my CPU spikes as the two pihole-FTL process fight.
can someone please point me in the right direction to investigate further?

Thanks in advance

01010101001

**Comment by diginc** [comment]
Could you see if FTL startup infinite loops when you run a stripped down container in the foreground?

`docker run -it --rm -e ServerIP="0.0.0.0" diginc/pi-hole:latest`

**Comment by 01010101001** [comment]
Thanks for the reply. Yes, the issue is the same when I use the command you provided. I still haven't managed to figure out what's going on...

root@hp-server:~# docker rm -f pihole
pihole
root@hp-server:~# docker run -it --rm -e ServerIP="0.0.0.0" diginc/pi-hole:latest
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
ARCH=amd64
BASH=/bin/bash
BASHOPTS=cmdhist:complete_fullquote:extquote:force_fignore:hostcomplete:interactive_comments:progcomp:promptvars:sourcepath
BASH_ALIASES=()
BASH_ARGC=()
BASH_ARGV=()
BASH_CMDS=()
BASH_LINENO=([0]="0")
BASH_SOURCE=([0]="/var/run/s6/etc/cont-init.d/20-start.sh")
BASH_VERSINFO=([0]="4" [1]="4" [2]="12" [3]="1" [4]="release" [5]="x86_64-pc-linux-gnu")
BASH_VERSION='4.4.12(1)-release'
CWD=/
DIRSTACK=()
EUID=0
GROUPS=()
HOME=/root
HOSTNAME=de4c000b296c
HOSTTYPE=x86_64
IFS=$' \t\n'
IPv6=True
MACHTYPE=x86_64-pc-linux-gnu
OPTERR=1
OPTIND=1
OSTYPE=linux-gnu
PATH=/opt/pihole:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PHP_ENV_CONFIG=/etc/lighttpd/conf-enabled/15-fastcgi-php.conf
PHP_ERROR_LOG=/var/log/lighttpd/error.log
PIHOLE_INSTALL=/tmp/ph_install.sh
PPID=207
PS4='+ '
PWD=/
S6OVERLAY_RELEASE=https://github.com/just-containers/s6-overlay/releases/download/v1.21.2.2/s6-overlay-amd64.tar.gz
S6_KEEP_ENV=1
SHELL=/bin/bash
SHELLOPTS=braceexpand:hashall:interactive-comments
SHLVL=1
ServerIP=0.0.0.0
TAG=debian
TERM=xterm
UID=0
_=bash
setupVars=/etc/pihole/setupVars.conf
 ::: Starting docker specific setup for docker diginc/pi-hole
Assigning random password: JnuiBWpr
+ [[ JnuiBWpr == '' ]]
+ pihole -a -p JnuiBWpr JnuiBWpr
  [✓] New password set
Using default DNS servers: 8.8.8.8 & 8.8.4.4
DNSMasq binding to default interface: eth0
Added ENV to php:
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
			"ServerIP" => "0.0.0.0",
			"VIRTUAL_HOST" => "0.0.0.0",
Using IPv4 and IPv6
::: Testing DNSmasq config: dnsmasq: syntax check OK.
::: Testing lighttpd config: Syntax OK
::: All config checks passed, starting ...
::: Docker start setup complete
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [i] Target: raw.githubusercontent.com (hosts)
  [✓] Status: Retrieval successful

  [i] Target: mirror1.malwaredomains.com (justdomains)
  [✓] Status: Retrieval successful

  [i] Target: sysctl.org (hosts)
  [✓] Status: Retrieval successful

  [i] Target: zeustracker.abuse.ch (blocklist.php?download=domainblocklist)
  [✓] Status: Retrieval successful

  [i] Target: s3.amazonaws.com (simple_tracking.txt)
  [✓] Status: Retrieval successful

  [i] Target: s3.amazonaws.com (simple_ad.txt)
  [✓] Status: Retrieval successful

  [i] Target: hosts-file.net (ad_servers.txt)
  [✓] Status: Retrieval successful

  [✓] Consolidating blocklists
  [✓] Extracting domains from blocklists
  [i] Number of domains being pulled in by gravity: 144497
  [✓] Removing duplicate domains
  [i] Number of unique domains trapped in the Event Horizon: 121530
  [i] Nothing to whitelist!
  [✓] Parsing domains into hosts format
  [✓] Cleaning up stray matter

  [✓] Force-reloading DNS service
pihole-FTL: no process found
  [✓] DNS service is running
  [✓] Pi-hole blocking is Enabled
[cont-init.d] 20-start.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting lighttpd
Starting dnsmasq
Starting crond
Starting pihole-FTL ()
FTL started!
[services.d] done.
dnsmasq: started, version 2.76 cachesize 10000
dnsmasq: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify
dnsmasq: using nameserver 8.8.4.4#53
dnsmasq: using nameserver 8.8.8.8#53
dnsmasq: read /etc/hosts - 7 addresses
dnsmasq: read /etc/pihole/local.list - 2 addresses
dnsmasq: failed to load names from /etc/pihole/black.list: No such file or directory
Starting pihole-FTL ()
Found pihole-FTL process with PID 451 (my PID 484) - killing it ...
Found pihole-FTL process with PID 451 (my PID 484) - killing it ...
Found pihole-FTL process with PID 451 (my PID 484) - killing it ...
Found pihole-FTL process with PID 451 (my PID 484) - killing it ...
Found pihole-FTL process with PID 451 (my PID 484) - killing it ...
Found pihole-FTL process with PID 451 (my PID 484) - killing it ...
Found pihole-FTL process with PID 451 (my PID 484) - killing it ...
Found pihole-FTL process with PID 451 (my PID 484) - killing it ...
FTL started!
dnsmasq: read /etc/pihole/gravity.list - 121530 addresses
Starting pihole-FTL ()
Found pihole-FTL process with PID 487 (my PID 495) - killing it ...
Found pihole-FTL process with PID 487 (my PID 495) - killing it ...
Found pihole-FTL process with PID 487 (my PID 495) - killing it ...
Found pihole-FTL process with PID 487 (my PID 495) - killing it ...
Found pihole-FTL process with PID 487 (my PID 495) - killing it ...
Found pihole-FTL process with PID 487 (my PID 495) - killing it ...
Found pihole-FTL process with PID 487 (my PID 495) - killing it ...
Found pihole-FTL process with PID 487 (my PID 495) - killing it ...
Found pihole-FTL process with PID 487 (my PID 495) - killing it ...
Found pihole-FTL process with PID 487 (my PID 495) - killing it ...
Found pihole-FTL process with PID 487 (my PID 495) - killing it ...
Found pihole-FTL process with PID 487 (my PID 495) - killing it ...
Found pihole-FTL process with PID 487 (my PID 495) - killing it ...
Found pihole-FTL process with PID 487 (my PID 495) - killing it ...
Found pihole-FTL process with PID 487 (my PID 495) - killing it ...
Found pihole-FTL process with PID 487 (my PID 495) - killing it ...
Found pihole-FTL process with PID 487 (my PID 495) - killing it ...
Found pihole-FTL process with PID 487 (my PID 495) - killing it ...
FTL started!
Starting pihole-FTL ()
Found pihole-FTL process with PID 497 (my PID 506) - killing it ...
Found pihole-FTL process with PID 497 (my PID 506) - killing it ...
Found pihole-FTL process with PID 497 (my PID 506) - killing it ...
Found pihole-FTL process with PID 497 (my PID 506) - killing it ...
Found pihole-FTL process with PID 497 (my PID 506) - killing it ...
Found pihole-FTL process with PID 497 (my PID 506) - killing it ...
Found pihole-FTL process with PID 497 (my PID 506) - killing it ...
Found pihole-FTL process with PID 497 (my PID 506) - killing it ...
Found pihole-FTL process with PID 497 (my PID 506) - killing it ...
Found pihole-FTL process with PID 497 (my PID 506) - killing it ...
Found pihole-FTL process with PID 497 (my PID 506) - killing it ...
Found pihole-FTL process with PID 497 (my PID 506) - killing it ...
Found pihole-FTL process with PID 497 (my PID 506) - killing it ...
(...)

**Comment by diginc** [comment]
Starting pihole-FTL () should be Starting pihole-FTL (no-daemon) in the latest version of the image.

Can you confirm your image hash and see if pulling gets you a newer copy?

```
~$ docker image ls diginc/pi-hole:latest
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
diginc/pi-hole      latest              eb902c685095        9 days ago          367MB
$ docker pull diginc/pi-hole:latest
latest: Pulling from diginc/pi-hole
Digest: sha256:50479369dcff346cb3f8aef12557ec8ebaf787882eeb7c0f44c98d7bcac39a52
Status: Image is up to date for diginc/pi-hole:latest
```

**Comment by 01010101001** [comment]
THANKS!

I just updated the image and started it again and the problem is gone! not sure what you changed but you fixed it. thanks a lot :)

**Comment by diginc** [comment]
There was a small window where the buggy image was released - more info here: 

https://github.com/diginc/docker-pi-hole/issues/257#issuecomment-380190798
