### ISSUE TITLE
pihole and dnsmasq running as root

### ISSUE THREAD

**Issue by teresaejunior** [diginc/docker-pi-hole#275]
This is a... 

- [x] Request for a new or modified feature
- [ ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

I have noticed that, although [install.sh exports USER=pihole](https://github.com/diginc/docker-pi-hole/blob/76d6a67d48f65d34c3991996339c34a39a82292f/install.sh#L26), pi-hole (and also dnsmasq) end up starting as root in the container. I have run the official `curl | bash` script and checked, and by default pi-hole is run with the user `pihole`, and dnsmasq with the user `dnsmasq`.

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version: Ubuntu 16.04.4
* Docker Version: 1.13.1-0ubuntu1~16.04.2
* Hardware architecture: x86_64

**Comment by diginc** [comment]
This is a docker difference I force append.  I tried running without user
root at first but dnsmasq would crash in docker without user=root appended
to the conf.  Other dnsmasq containers implemented similar workarounds,
can't recall the reason.  That change was ages ago during initial
development of the container though so maybe things have changed for
dnsmasq in docker.

**Comment by nxadm** [comment]
As a sidenote, it's possible to run docker containers with root on the inside and an non-priviledged user on the outside: https://docs.docker.com/engine/security/userns-remap/

Depending on your use, this may be a good fit.

**Comment by teresaejunior** [comment]
Thanks, I'll try that! My use case is that of someone who is becoming paranoid about security... I need a rest.
