### ISSUE TITLE
Trouble mounting /var/log as a volume

### ISSUE THREAD

**Issue by gmrza** [diginc/docker-pi-hole#276]
I am trying to mount /var/log inside the container onto a path on a host filesystem which is mounted as a ramfs, but am running into problems.  My intention is to be able to log to a ramfs in order to avoid excessive writes to the SD card on a Pi3B+.

This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

When I try to mount /var/log as a volume, it appears that the volume is only mounted after some of the daemons start.  Only the pihole and pihole-FTL logs are visible - indicating that the volume was probably mounted over the other logs.  Also lighttpd fails.
## Expected Behavior

/var/log should be mounted before other daemons start.
## Actual Behavior

Instead, the volume appears to be getting mounted at some stage after dnsmasq starts.  
## Steps to Reproduce and debugging done

I am creating the container using docker-compose.  My docker-compose.yml file includes the following lines:

version: '3.3'
services:
  pihole:
    restart: unless-stopped
    container_name: pihole
    volumes:
      - /var/pihole:/etc/pihole
      - /var/dnsmasq.d:/etc/dnsmasq.d
      - /var/log/pihole:/var/log
    image: diginc/pi-hole-multiarch:debian_armhf
    environment:
      - ServerIP=172.16.137.49
      - VIRTUAL_HOST=dockhole
      - TZ=Australia/Melbourne
      - WEBPASSWORD=pihole
      - DNS1=172.16.138.10
      - DNS2=""
      - IPv6=False
      - DNSMASQ_LISTENING=all
    ports:
      - "172.16.137.49:53:53/tcp"
      - "172.16.137.49:53:53/udp"
      - "172.16.137.49:80:80"

## Debug steps I have tried

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [ ] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version:
Raspberyy Pi 3B+, Raspbian Stretch
* Docker Version:
Docker version 18.05.0-ce, build f150324

* Hardware architecture: 
ARMv7 (Pi3B+)

**Comment by nxadm** [comment]
The bind mounting happens before the container starts, so I don't think it can be explained as you write. Maybe the other daemons don't have the correct right to write in the mounted dir?

**Comment by eku** [comment]
Did you try to add option ```Z``` to the volume line, i.e. ```/var/log/pihole:/var/log:Z```. I had the same problem on Fedora and that option worked.

**Comment by gmrza** [comment]
It seems to be caused by the way Docker layers mounts.  lighttpd expects its log directory to be there and fails if it is not.
A workaround that seems to work is to mount individual files, and then the directory for lighttpd.  What may be more elegant is to create a log dir with the lighttpd directory in it and mount that.  log2ram on the RPi will take care of making sure it is created again on reboot.

Currently my docker-compose.yml looks like this:

version: '3.3'
services:
  pihole:
    restart: unless-stopped
    container_name: pihole
    volumes:
      - /var/pihole:/etc/pihole
      - /var/dnsmasq.d:/etc/dnsmasq.d
      - /var/log/pihole/pihole.log:/var/log/pihole.log
      - /var/log/pihole/pihole-FTL.log:/var/log/pihole-FTL.log
      - /var/log/lighttpd:/var/log/lighttpd
    image: diginc/pi-hole-multiarch:debian_armhf
    environment:
      - ServerIP=172.16.137.49
      - VIRTUAL_HOST=dockhole
      - TZ=Australia/Melbourne
      - WEBPASSWORD=********
      - DNS1=172.16.138.10
      - DNS2=""
      - IPv6=False
      - DNSMASQ_LISTENING=all
    ports:
      - "172.16.137.49:53:53/tcp"
      - "172.16.137.49:53:53/udp"
      - "172.16.137.49:80:80"
