### ISSUE TITLE
Tag debian_armhf not found in repository docker.io/diginc/pi-hole-multiarch  on Pi B

### ISSUE THREAD

**Issue by hoehlenknarf** [diginc/docker-pi-hole#282]
This is a... 

- [ ] Request for a new or modified feature
- [x ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description
Running image "diginc/pi-hole-multiarch:debian_armhf'"  fails with message 
"Pulling repository docker.io/diginc/pi-hole-multiarch
Tag debian_armhf not found in repository docker.io/diginc/pi-hole-multiarch"

Same behavior for IMAGE="diginc/pi-hole-multiarch:v3.2.1_debian_armhf" .

## Expected Behavior

Container should start
## Actual Behavior

Error message "Tag debian_armhf not found in repository docker.io/diginc/pi-hole-multiarch"
## Steps to Reproduce and debugging done

> cat pihole_dockerstart.sh
#!/bin/bash
IP="x.x.x.x"
IMAGE="diginc/pi-hole-multiarch:debian_armhf"
docker run -d \
    --name pihole \
    -p 53:53/tcp -p 53:53/udp -p 8080:80 \
    -v "/var/pihole/etc/pihole/:/etc/pihole/" \
    -v "/var/pihole/etc/dnsmasq.d/:/etc/dnsmasq.d/" \
    -e ServerIP="${IP}" \
    -e ServerIPv6="${IP}" \
    -e WEBPASSWORD="xxx" \
    $IMAGE

> ./pihole_dockerstart.sh
Unable to find image 'diginc/pi-hole-multiarch:debian_armhf' locally
debian_armhf: Pulling from diginc/pi-hole-multiarch
7d12f6723df1: Pulling fs layer
c07419110c20: Pulling fs layer
0c1b6c4f7387: Pulling fs layer
d4f11dddcfbf: Pulling fs layer
7b38b7b6bf6c: Pulling fs layer
960c3c0a10ad: Pulling fs layer
0761c053d271: Pulling fs layer
eb3a998a08c9: Pulling fs layer
91395d9b6692: Pulling fs layer
e4ed770685c5: Pulling fs layer
3e996ca6e1b1: Pulling fs layer
1e0f673177e3: Pulling fs layer
10a233e68ff4: Pulling fs layer
e68fa0a6c6a8: Pulling fs layer
311f591bd519: Pulling fs layer
8ae0345119fa: Pulling fs layer
dc77652eea0a: Pulling fs layer
5e07e2110ee5: Pulling fs layer
dba77570503c: Pulling fs layer
1e7f3721ebd5: Pulling fs layer
bb1aa15d6449: Pulling fs layer
013b9d4f5c54: Pulling fs layer
c182c93c39ce: Pulling fs layer
60a4efc46158: Pulling fs layer
2095e8c1df2e: Pulling fs layer
bbab7746eb92: Pulling fs layer
1f5fcaf402bb: Pulling fs layer
03f33794c18c: Pulling fs layer
d7d404766857: Pulling fs layer
2d7a6991f348: Pulling fs layer
Pulling repository docker.io/diginc/pi-hole-multiarch
Tag debian_armhf not found in repository docker.io/diginc/pi-hole-multiarch

## Debug steps I have tried

- [ ] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [x] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar 

## Your Environment 

* Docker Host Operating System and OS Version:
Raspbian GNU/Linux 9 \n \l
* Docker Version:
Docker version 1.8.3, build f4bf5c7
* Hardware architecture: 
Linux xxx 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux

**Comment by diginc** [comment]
What does `docker images -a | grep diginc` say?

I'll get my RBP2 out tonight to try this out.

**Comment by hoehlenknarf** [comment]
>docker images -a | grep diginc
>docker images -a
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
hello-world         latest              82305ea4d159        8 weeks ago         1.848 kB
<none>              <none>              24b9d95168dd        8 weeks ago         1.848 kB
>

**Comment by hoehlenknarf** [comment]
Running the command with "--debug=true" produces the following output in daemon.log:


```
Jun  7 20:36:14 xxx docker[2528]: time="2018-06-07T20:36:14.033877887+02:00" level=info msg="POST /v1.20/containers/create?name=pihole"
Jun  7 20:36:14 xxx docker[2528]: time="2018-06-07T20:36:14.036163086+02:00" level=warning msg="Your kernel does not support memory swappiness capabilities, memory swappiness discarded."
Jun  7 20:36:14 xxx docker[2528]: time="2018-06-07T20:36:14.036935531+02:00" level=error msg="Handler for POST /containers/create returned error: No such image: diginc/pi-hole-multiarch:debian_armhf (tag: debian_armhf)"
Jun  7 20:36:14 xxx docker[2528]: time="2018-06-07T20:36:14.037227613+02:00" level=error msg="HTTP Error" err="No such image: diginc/pi-hole-multiarch:debian_armhf (tag: debian_armhf)" statusCode=404
Jun  7 20:36:14 xxx docker[2528]: time="2018-06-07T20:36:14.040690829+02:00" level=info msg="POST /v1.20/images/create?fromImage=diginc%2Fpi-hole-multiarch&tag=debian_armhf"
Jun  7 20:36:31 xxx docker[2528]: time="2018-06-07T20:36:31.925139737+02:00" level=error msg="error copying from layer download progress reader: download canceled Head https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/20/2085e71d2cd9fa1e02d51679220153aebecbcab5ddce70b628f66adf7a90ffc8/data?verify=1528399577-7OBLPUpsDf9PPP87GQGwa7X3q4Q%3D: net/http: TLS handshake timeout"
```

Using wget i can download the given URL:

```
>wget https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/20/2085e71d2cd9fa1e02d51679220153aebecbcab5ddce70b628f66adf7a90ffc8/data?verify=1528399577-7OBLPUpsDf9PPP87GQGwa7X3q4Q%3D

Auflösen des Hostnamens »production.cloudflare.docker.com (production.cloudflare.docker.com)« … 104.18.124.25, 104.18.123.25, 104.18.121.25, ...
Verbindungsaufbau zu production.cloudflare.docker.com (production.cloudflare.docker.com)|104.18.124.25|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
Länge: 45554731 (43M) [application/octet-stream]
Wird in »»data?verify=1528399577-7OBLPUpsDf9PPP87GQGwa7X3q4Q%3D«« gespeichert.

BLPUpsDf9PPP87GQGwa7X3q4Q%3D                  75%[===========================================================================>                         ]  32,83M  3,08MB/s    eta 4s     
data?verify=1528399577-7OBLPUpsDf9PPP87GQGwa7X3 100%[====================================================================================================>]  43,44M  2,88MB/s    in 18s     

2018-06-07 20:42:03 (2,47 MB/s) - »»data?verify=1528399577-7OBLPUpsDf9PPP87GQGwa7X3q4Q%3D«« gespeichert [45554731/45554731]

> file data\?verify\=1528399577-7OBLPUpsDf9PPP87GQGwa7X3q4Q%3D 
data?verify=1528399577-7OBLPUpsDf9PPP87GQGwa7X3q4Q%3D: gzip compressed data

> ls -l data\?verify\=1528399577-7OBLPUpsDf9PPP87GQGwa7X3q4Q%3D 
-rw-r--r-- 1 root root 45554731 Nov 21  2017 data?verify=1528399577-7OBLPUpsDf9PPP87GQGwa7X3q4Q%3D
```

**Comment by visibilityspots** [comment]
what does a simple docker pull gives you?
```
$ docker pull diginc/pi-hole-multiarch:debian_armhf
debian_armhf: Pulling from diginc/pi-hole-multiarch
2085e71d2cd9: Pull complete 
c6ab3af45a5c: Pull complete 
b75f3e1dedf6: Pull complete 
6e34d31c9068: Pull complete 
7b70e6a38229: Pull complete 
267ab3ce219f: Pull complete 
18e0db938c4c: Pull complete 
Digest: sha256:c9810347cf2d4b9a92801d78eddd70cf7a44991f9009f93f6a3c8b0c2bdf3107
Status: Downloaded newer image for diginc/pi-hole-multiarch:debian_armhf
```

**Comment by hoehlenknarf** [comment]
```
docker pull diginc/pi-hole-multiarch:debian_armhf
debian_armhf: Pulling from diginc/pi-hole-multiarch

7d12f6723df1: Pulling fs layer 
c07419110c20: Pulling fs layer 
0c1b6c4f7387: Pulling fs layer 
d4f11dddcfbf: Pulling fs layer 
7b38b7b6bf6c: Pulling fs layer 
960c3c0a10ad: Pulling fs layer 
0761c053d271: Pulling fs layer 
eb3a998a08c9: Pulling fs layer 
91395d9b6692: Pulling fs layer 
e4ed770685c5: Pulling fs layer 
3e996ca6e1b1: Pulling fs layer 
1e0f673177e3: Pulling fs layer 
10a233e68ff4: Pulling fs layer 
e68fa0a6c6a8: Pulling fs layer 
311f591bd519: Pulling fs layer 
8ae0345119fa: Pulling fs layer 
dc77652eea0a: Pulling fs layer 
5e07e2110ee5: Pulling fs layer 
dba77570503c: Pulling fs layer 
1e7f3721ebd5: Pulling fs layer 
bb1aa15d6449: Pulling fs layer 
013b9d4f5c54: Pulling fs layer 
c182c93c39ce: Pulling fs layer 
60a4efc46158: Pulling fs layer 
2095e8c1df2e: Pulling fs layer 
bbab7746eb92: Pulling fs layer 
1f5fcaf402bb: Pulling fs layer 
03f33794c18c: Pulling fs layer 
d7d404766857: Pulling fs layer 
2d7a6991f348: Pulling fs layer 
Pulling repository docker.io/diginc/pi-hole-multiarch
Tag debian_armhf not found in repository docker.io/diginc/pi-hole-multiarch

```

deamon.log says: 

```
Jun 14 20:46:52 xxx docker[369]: time="2018-06-14T20:46:52.998872064+02:00" level=info msg="POST /v1.20/images/create?fromImage=diginc%2Fpi-hole-multiarch%3Adebian_armhf"
Jun 14 20:47:11 xxx docker[369]: time="2018-06-14T20:47:11.205691169+02:00" level=error msg="error copying from layer download progress reader: download canceled Head https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/20/2085e71d2cd9fa1e02d51679220153aebecbcab5ddce70b628f66adf7a90ffc8/data?verify=1529005017-IIc3Tn8ICyLbEcaM6rx0pvtauo8%3D: net/http: TLS handshake timeout"
```

**Comment by diginc** [comment]
Can you pull `hello-world` image or another image?  (not sure if hello-world has arm version)

**Comment by notarock** [comment]
I had the same issue as OP with raspberrypi 3 B+ , and was able to pull `hello-world` succesfully but not this image.

What I did is remove/purge `docker.io` and re-installed it using `curl -sSL get.docker.com | sh` and then i was able to pull the image. You can view the script's source [here](https://get.docker.com/) 

Hope this help!

**Comment by hoehlenknarf** [comment]
Pulling the hello-world image worked fine (see one of my previous posts).

As suggested by noarock, i purged the docker.io package coming along with raspberian stretch and installed it using `curl -sSL get.docker.com | sh `. 
After that, pulling and running the image works fine.  

Thanks for your help!
