### ISSUE TITLE
Docker image doesn't update to version 3.3

### ISSUE THREAD

**Issue by jerheij** [diginc/docker-pi-hole#291]
I just installed the docker image on a freshly installed Debian and docker CE installation bit the pihole webinterface keeps saying it's version 3.0.

I've tried a repull of the docker image and that didn't help. I am using docker-compose in combination with the yaml that's provided on the installation page.

## Your Environment 
* Docker Host Operating System and OS Version:Debian 9.4.x
* Docker Version:Debian/latest
* Hardware architecture: x86_64

**Comment by diginc** [comment]
Can you confirm you're using one of the image that says uploaded 3 months ago?  https://store.docker.com/community/images/diginc/pi-hole/tags

When you run `docker images` or `docker pull diginc/pi-hole` what is the hash of the image?  I'll confirm I pull the exact same hash and see what version it has.

**Comment by jerheij** [comment]
I confirm the image I am using is uploaded  three months ago:

```
# docker images |grep pi-hole
diginc/pi-hole           latest              eb902c685095        3 months ago        367
```

**Comment by diginc** [comment]
That's the same image I have.  pihole-FTL is 3.0 (the latest released version of that) but the web and core versions are 3.0

What does this CLI report for versions? 

```
docker run -it --entrypoint bash diginc/pi-hole:latest pihole -v
```

**Comment by jerheij** [comment]
I feel stupid now. The Pi-hole version is indeed 3.3. It's the FTL version I was looking at and you see in the web interface. That's what got me confused.

Thanks anyway!
