### ISSUE TITLE
Remove Recommendation for /etc/dnsmasq.d volume

### ISSUE THREAD

**Issue by StefanSchoof** [diginc/docker-pi-hole#294]
The Readme recommend to have a volume for the `/etc/dnsmasq.d` folder. 

This is a... 

- [ ] Request for a new or modified feature
- [ ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

The `/etc/dnsmasq.d` folder contains on default only one file in which the header says this should not edited directly. If the needed options in this file changes a update is easier if this file is changed in the docker image instead of every user update his file manually or have a script doing this.

## Possible Fix

Change the documentation to have the volume only optinal, if you have the need to store extra files in the `/etc/dnsmasq.d`. Remove this folder from the example run command and the example docker-compose.yml.

**Comment by diginc** [comment]
> If the needed options in this file changes a update is easier if this file is changed in the docker image instead of every user update his file manually or have a script doing this.

Persisting web-UI to servers is the main goal of this volume.  I think an average user should be able to expect if they change the setting through an official Pi-hole interface it should stick by default.  It also allows adding more dnsmasq.d configs besides 01-pihole.conf.   At first I thought there was just one file in there too but it seems there are now many if you review the pi-hole source : https://github.com/pi-hole/pi-hole/search?q=dnsmasq.d&unscoped_q=dnsmasq.d (DHCP mainly).

**Comment by StefanSchoof** [comment]
I did not think about that. You are right.
