### ISSUE TITLE
FTLDNS

### ISSUE THREAD

**Issue by MASNathan** [diginc/docker-pi-hole#295]
This is a... 

- [x] Request for a new or modified feature
- [ ] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

Thank you for what you have done so far! 

I'm looking to combine Unbound and Pihole as they suggest on [this blog post](https://pi-hole.net/2018/06/09/ftldns-and-unbound-combined-for-your-own-all-around-dns-solution/) but for that we need to use FTLDNS, which is not available at the moment using `diginc/pi-hole-multiarch:debian_armhf`.

I've seen that you have been tinkering with FTLDNS, is there a ETA for the FTLDNS image to be rolled-out?

**Comment by diginc** [comment]
FTLDNS is still beta, are you requesting a prerelease / beta version for ARM?  Sure thing 👍

**Comment by diginc** [comment]
Done !  https://hub.docker.com/r/diginc/pi-hole-multiarch/tags/

`diginc/pi-hole-multiarch:debian_aarch64_prerelease`
`diginc/pi-hole-multiarch:debian_armhf_prerelease`

**Comment by MASNathan** [comment]
Well sir, you rock
