### ISSUE TITLE
Set up arm automated build

### ISSUE THREAD

**Issue by diginc** [diginc/docker-pi-hole#35]
Docker hub is x86 only.  The end solution will probably be a 3rd party building the images on arm hardware and pushing to a non-automated repository on docker hub.  

I could setup a local build on my 2 pis and automated it my own own infrastructure but I'd like to avoid that.  Partly to avoid maintenance long term and partly to publish the build logs through a 3rd party service in the spirit of open source.

Related  #2 #28 #30

**Comment by firecyberice** [comment]
Have a look at https://hub.docker.com/u/armhf for arm based images. They are build as arm versions of the official library.

**Comment by diginc** [comment]
Thanks @firecyberice - I see armhf seems to use jenkins jobs to swap out the FROM and other arm specific changes but I haven't found where those actual jenkins jobs live/execute.  Do you know if they run on a private jenkins cluster rather than a free build as a service platform?

This looks pretty promising for building multi-arch on Hub : https://resin.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/

**Comment by firecyberice** [comment]
This resin method works only with debian images (I have tried to build alpine this way) and uses qemu to emulate arm.

The jenkins cluster is private and maintained by Docker.

**Comment by diginc** [comment]
@JSurf have you successfully used the qemu shims with your alpine image? https://github.com/JSurf/docker-rpi-alpine 

I've been looking at your images as a potential base for mine since you have a regularly updated autobuild of resin + qemu shim ready to go.

**Comment by diginc** [comment]
#38 put the source for arm into my dev branch and I built it on hub with the `diginc/pi-hole:arm_dev` tag.  Seems @firecyberice is correct that alpine most likely doesn't have all it's kinks worked out yet so it'll just be debian/raspbian for now.

I'll update readme with details on the new tag when it is merged into master.  

Comments are still open if other have ideas/feedback here, but my original goal has been accomplished in what I feel was the simplest fashion.
