### ISSUE TITLE
Custom Config /etc/dnsmasq.d

### ISSUE THREAD

**Issue by jodumont** [diginc/docker-pi-hole#37]
**Great Job !! **

But I still having issue with customizing : /etc/dnsmasq.d/01-pihole.conf
even i'm using -v /srv/etc/dnsmasq.d:/etc/dnsmasq.d or /srv/etc/dnsmasq.d:/etc/dnsmasq.d:ro
something replace my :
addn-hosts=/etc/pihole/mylist.list by addn-hosts=/etc/pihole/gravity.list

Even by making the change into 01-pihole.conf before docker build .
The result is the same.

Strangely others modification on that file still after a reboot.

I also tried by making a 02-mylist.conf and when i'm doing that it simply don't start.

:(

**Comment by diginc** [comment]
Could you please provide a sample of your docker run command and config customization in code blocks so I can try to reproduce this as closely as possible?

Are  you running the latest/alpine tag or debian?  `docker images | grep 'pi-hole'` can tell you the version of your images.

I'm not sure if it'll matter but it maybe helpful if you pasted the output of `docker info` too.

**Comment by jodumont** [comment]
Hi!
My Bad i'll transfert my issue to : https://github.com/pi-hole/pi-hole/blob/master/gravity.sh
Because the issue is around the 328 line.

```
#Now replace the line in dnsmasq file
${SUDO} sed -i "s/^addn-hosts.*/addn-hosts=$adList/" /etc/dnsmasq.d/01-pihole.conf
dnsmasqPid=$(pidof dnsmasq)

```
It need a if or something like that (but I don't know).
