### ISSUE TITLE
Confirm IPV6 Blocking

### ISSUE THREAD

**Issue by diginc** [diginc/docker-pi-hole#43]
From docker hub comments:

> yan1000, a month ago
> hi, it doesn't block ipv6 address ads ? didn't add ipv6 support ? thx

Similar to the first bug I had with this container for IPv4, without the Docker Host's IP the pihole will find and return the internal docker IPv6 IP for ads, so it never hits the blank lighttpd assets.  

I think a ServerIPv6 environment variable, similar to ServerIP env var, should fix this problem.
#39 and #40 also related

**Comment by diginc** [comment]
https://github.com/diginc/docker-pi-hole/commit/ee2949aba82346ee5f0fdbe7c19f563b067f48f6 added the ipv6 setupVar required that docker's AdminLTE was erroring out on finding.  It'll also be used by gravity to generate the ipv6 lists I believe.

**Comment by soredake** [comment]
ping? ipv6 blocking is now working for me for now.

**Comment by soredake** [comment]
Adding `IP6=$(ip addr show eth0 | grep "inet6\b" | awk '{print $2}' | head -n1 | cut -d/ -f1)` and `-e ServerIPv6="$IP6" \` enables ipv6 blocking for me.
