### ISSUE TITLE
PHP 5.6.25 Vulnerabilities

### ISSUE THREAD

**Issue by dbec** [diginc/docker-pi-hole#44]
When possible can you patch the PHP5? 
Refer to:
https://msisac.cisecurity.org/advisories/2016/2016-142.cfm
Thanks,
Daniel

**Comment by diginc** [comment]
Rebuilding the container now, I float to the latest php so if the fix is patched to debian and alpine repositories then the rebuild should pull in the fix.  I will confirm later.

**Comment by diginc** [comment]
alpine seems to be sitting a little prettier than debian but neither are on the 26 release.

```
$ docker run -it --entrypoint bash diginc/pi-hole:alpine -c 'php -v'
PHP 5.6.25 (cli) (built: Sep 21 2016 23:54:53) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
$ docker run -it --entrypoint bash diginc/pi-hole:debian -c 'php -v'
PHP 5.6.24-0+deb8u1 (cli) (built: Jul 26 2016 08:17:07) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

Using this image maybe easier since they build php to get the latest version: https://hub.docker.com/_/php/

**Comment by dbec** [comment]
It looks like the standard Alpine repositories now have php 5.6.26.

**Comment by diginc** [comment]
I rebuilt for the latest version of pi-hole web last night and looks like it grabbed 5.6.26 in alpine.  For debian I'll still experiment with the compiled  up to date PHP container.

**Comment by diginc** [comment]
debian eventually caught up: "PHP 5.6.26-0+deb8u1 (cli) (built: Sep 21 2016 12:37:50)" .  I'll still think about swapping the mainline debian out for the php custom build image.
