### ISSUE TITLE
Replace `pihole -up` with suggestion to docker pull / rm / up instead

### ISSUE THREAD

**Issue by diginc** [diginc/docker-pi-hole#49]
docker exec pihole pihole -up fails per: https://github.com/pi-hole/AdminLTE/issues/150#issuecomment-250919266

```
fatal: Not a git repository (or any of the parent directories): .git
/usr/local/bin/pihole: line 59: /etc/.pihole/automated install/basic-install.sh: No such file or directory
```
### Why is it broken?

Since I do not add any of the git repositories data like the official pihole install, the update method they use is broken.  This keeps my container size lower and docker users have the `docker pull` + `docker rm` + `docker up` container upgrade path.  docker rm shouldn't remove any important data if you setup volume maps for your critical data.
### What to do?

I'm thinking of stubbing that functionality with a echo'd suggestion to throw your old container away and pull the latest version, then re-create the container using the latest base image.
### Why refuse to just make `pihole -up` just work?

I suppose I could support the rolling update method and let people do this if they really wanted to but I'd at least want to warn them that they are going down an unsupported path and the first thing I'd tell them is to destroy their container and re-create it if they hit any strange behavior.  If they did and suddenly had an old version I'd know they hadn't pulled the latest version.

The docker way is to stay in-line with what latest version is on the docker hub/cloud so we're all Identical and not snowflakes.   By updating locally you're forking at a old point in time and could run into bugs that would be unique to you since everyone else is updating from a common base image off hub, which has consistent tested behavior.

**Comment by mjgiardino** [comment]
Could you elaborate on the preferred method of updating pi-hole docker images? I'm just getting started with docker and I'm not clear on the right procedure.

Thanks for you work!

**Comment by diginc** [comment]
I was just updating the Readme for the next update pull request #61.

I'll be pushing it in a few minutes and everything should be merged to the master branch by tomorrow.

**Comment by diginc** [comment]
Sneak peak on what I'm about to push to readme: 

### Upgrading                                                                                                       

For those unfamilar, the docker way to ugprade is:

1) Throw away your container: `docker rm -f pihole`
2) Download the latest version of the image: `docker pull diginc/pi-hole`
3) Start your container with the newer base image: `docker run ... diginc/pi-hole` (whatever your original run command was)

Why is this style of upgrading good?  A couple reasons: Everyone is starting from the same base which has been tested to known to work.  No worrying about upgrading from A to B, B to C, or A to C is required for application developers.

**If you try to use `pi-hole -up` it will fail**, more about this is covered in [Issue 49](https://github.com/diginc/docker-pi-hole/issues/49)

**Comment by diginc** [comment]
Released refined instructions for updating to the `master` branch
