### ISSUE TITLE
no internet access

### ISSUE THREAD

**Issue by Symbiot78** [diginc/docker-pi-hole#5]
hi

I think I got the docker running.. however in the webadmin interface the graphics aren't loading.

this is pihole on a VM I'm running:

![serverinstall](https://cloud.githubusercontent.com/assets/3314249/14061169/ec3096e8-f379-11e5-977b-b3628cb6c8de.png)

and this is webadmin Docker image.

![docker](https://cloud.githubusercontent.com/assets/3314249/14061170/f3946310-f379-11e5-9be0-e033dd2c91f0.png)

as you can see not running properly.. 

this is the "details":

`[
    {
        "Id": "5ab45a7d23842a6bc114ec617eff54291cb83548cae9e922404048b57281b579",
        "Created": "2016-03-26T16:10:31.816740894Z",
        "Path": "tini",
        "Args": [
            "--",
            "/bin/sh",
            "-c",
            "/start.sh"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 52239,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2016-03-26T16:10:32.173696045Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:53ad0218709ccfea1c774232432480372234dd231e7220bc6effe2a3bd15d48d",
        "ResolvConfPath": "/var/lib/docker/containers/5ab45a7d23842a6bc114ec617eff54291cb83548cae9e922404048b57281b579/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/5ab45a7d23842a6bc114ec617eff54291cb83548cae9e922404048b57281b579/hostname",
        "HostsPath": "/var/lib/docker/containers/5ab45a7d23842a6bc114ec617eff54291cb83548cae9e922404048b57281b579/hosts",
        "LogPath": "/var/lib/docker/containers/5ab45a7d23842a6bc114ec617eff54291cb83548cae9e922404048b57281b579/5ab45a7d23842a6bc114ec617eff54291cb83548cae9e922404048b57281b579-json.log",
        "Name": "/Pihole",
        "RestartCount": 0,
        "Driver": "aufs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/etc/localtime:/etc/localtime:ro",
                "/var/log/pihole.log:/var/log/pihole.log",
                "/etc/pihole/whitelist.txt:/etc/pihole/whitelist.txt",
                "/etc/pihole/blacklist.txt:/etc/pihole/blacklist.txt"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "bridge",
            "PortBindings": {
                "53/tcp": [
                    {
                        "HostIp": "192.168.1.123",
                        "HostPort": "53"
                    }
                ],
                "53/udp": [
                    {
                        "HostIp": "192.168.1.123",
                        "HostPort": "53"
                    }
                ],
                "80/tcp": [
                    {
                        "HostIp": "192.168.1.123",
                        "HostPort": "8053"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "ShmSize": 67108864,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "KernelMemory": 0,
            "Memory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null
        },
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "Mounts": [
            {
                "Source": "/var/log/pihole.log",
                "Destination": "/var/log/pihole.log",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/etc/pihole/whitelist.txt",
                "Destination": "/etc/pihole/whitelist.txt",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/etc/pihole/blacklist.txt",
                "Destination": "/etc/pihole/blacklist.txt",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/etc/localtime",
                "Destination": "/etc/localtime",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "pihole",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "53/tcp": {},
                "53/udp": {},
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "/start.sh"
            ],
            "Image": "diginc/pi-hole:latest",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "tini",
                "--"
            ],
            "OnBuild": null,
            "Labels": {},
            "StopSignal": "SIGTERM"
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "d94056c04420fad07df10f47a328234f2db431ec6b06765263d6ebcd9325fd25",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "53/tcp": [
                    {
                        "HostIp": "192.168.1.123",
                        "HostPort": "53"
                    }
                ],
                "53/udp": [
                    {
                        "HostIp": "192.168.1.123",
                        "HostPort": "53"
                    }
                ],
                "80/tcp": [
                    {
                        "HostIp": "192.168.1.123",
                        "HostPort": "8053"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/d94056c04420",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "4d4d4329506cd654e2ac8528362b2663f13dedc5720989e662a7c6eb9061c055",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "ad53359efd98fd5b96b3eab9fef7689ab20905f8cc4b735c319237ce985c29a0",
                    "EndpointID": "4d4d4329506cd654e2ac8528362b2663f13dedc5720989e662a7c6eb9061c055",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02"
                }
            }
        }
    }
]`

**Comment by Symbiot78** [comment]
hm.. I refreshed the page (yes yes, should've done that at once but alas)

more graphics is loading now but not all.... 

![afterwebifrefresh](https://cloud.githubusercontent.com/assets/3314249/14061201/c847f400-f37a-11e5-9df1-62024310c3e4.png)

**Comment by Symbiot78** [comment]
damnit.. not that works as well.. seems it took it's time getting up & running.. 
I've turned of my VM to test the docker image.. 

what about updating the pi-hole itself? I assume I cannot do the "curl -L install.pi-hole.net | bash" ?

**Comment by diginc** [comment]
I just kicked off a new build with the latest code baked into the docker containers.  pi-hole repo had superficial updates it seems and AdminLTE (web interface) had a few lines of php code changed.

I'm getting this error right now too (I hadn't looked) and it appears to be an 500 error from PHP:

could you search the docker logs for any errors like this?

`docker logs --tail=100 <your_container_name> | grep error`

Or you could open web developer tools (firefox/chome) and check the network tab for 500 errors like I had:

"NetworkError: 500 Internal Server Error - http://pihole.diginc.lan/admin/api.php?overTimeData"
api.php...imeData
"NetworkError: 500 Internal Server Error - http://pihole.diginc.lan/admin/api.php?summaryRaw&topItems"
api.php...opItems
"NetworkError: 500 Internal Server Error - http://pihole.diginc.lan/admin/api.php?summary"

**Comment by diginc** [comment]
My log wasn't really over the limit but I'm wondering if the php script isn't multiplying the size of the log in memory consumption during processing of it.  Starting with a fresh /var/log/pihole.log seemed to solve my 500 errors.

```
docker exec -it lanhelpers_pihole_1 grep -r memory_limit /etc/php
/etc/php/php-fpm.conf:;php_admin_value[memory_limit] = 32M
/etc/php/php.ini:memory_limit = 128M

docker exec -it lanhelpers_pihole_1 du -sh /var/log/pihole.log   
27.7M   /var/log/pihole.log
```

**Comment by Symbiot78** [comment]
I edited my last post... 
I didn't mean "not" .. i meant NOW... 
after a browser refresh it works... all of it... I think...

is it me.. or does this docker behave differently than the original pi-hole.. 
I haven't tested but I'm noticing that sites with ads take a LOOOOOONG time to load... it seems like the browser is waiting for each ad-load to timeout.

if you try hitting this url: http://thestir.cafemom.com/entertainment/158359/glee_changes_already_under_way?utm_medium=sem2&utm_campaign=prism&utm_source=outbrain&utm_content=0

you'll see it take forever to finish loading.. 

I never noticed this in the old pi-hole.. 

is it serving a blank image instead of the ads?

**Comment by Symbiot78** [comment]
about the logs I'm seeing no errors (now).. 

I updated the docker image to your newest.. same issue with sites loading.

**Comment by diginc** [comment]
You are totally right.  All the ads have just been timing out when loading because I had populated the address to return as the internal docker container IP rather than the docker HOST ip. 

A quick fix is to volume map your docker host IP from a file on your host to /tmp/piholeIP inside the container.

You also need to make sure pihole container is the default service on port 80.  They built in a nice DNS name to test this - if you can goto http://Pi-Hole.IsWorking.OK/admin then things should be happy.

I'll try to iron out the details and update the readme soon.

**Comment by Symbiot78** [comment]
Hi

thx.. I'm not quite following the volumemapping ip thingy but I'll keep a lookout for updates to the docker. Meantime I'll start up my VM again..

**Comment by diginc** [comment]
Hey @Symbiot78 - please take a look at the readme changes I made in #7 and see if the [docker_run.sh](https://github.com/diginc/docker-pi-hole/blob/master/docker_run.sh) works for you.

The page you referenced does not time out for me anymore (though it does take short while to load) when using that startup method.
