### ISSUE TITLE
Error loading html/admin/data.php

### ISSUE THREAD

**Issue by srygaard** [diginc/docker-pi-hole#50]
I'm on the latest version of pihole that was released today.  I'm not sure if this happens on the older version(s).

Pi-hole Version V2.9.1 
Web Interface Version v1.4.2
Platform: Unraid 6.2

I see the following repeated errors in the logs but everything appears to work otherwise.  Is this why the logs need to be flushed using the cron?

```
==> /var/log/nginx/access.log <==
192.168.1.179 - - [01/Oct/2016:19:01:22 +0000] "GET /admin/api.php?summary HTTP/1.1" 200 128 "http://192.168.1.10/admin/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.41 Safari/537.36"

==> /var/log/nginx/error.log <==

2016/10/01 19:01:22 [error] 224#224: *1 FastCGI sent in stderr: "PHP message: PHP Warning: parse_ini_file(/etc/pihole/setupVars.conf): failed to open stream: No such file or directory in /var/www/html/admin/data.php on line 3" while reading response header from upstream, client: 192.168.1.179, server: , request: "GET /admin/api.php?summary HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.1.10", referrer: "http://192.168.1.10/admin/"


==> /var/log/nginx/access.log <==
192.168.1.179 - - [01/Oct/2016:19:01:33 +0000] "GET /admin/api.php?summary HTTP/1.1" 200 128 "http://192.168.1.10/admin/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.41 Safari/537.36"

==> /var/log/nginx/error.log <==

2016/10/01 19:01:33 [error] 224#224: *1 FastCGI sent in stderr: "PHP message: PHP Warning: parse_ini_file(/etc/pihole/setupVars.conf): failed to open stream: No such file or directory in /var/www/html/admin/data.php on line 3" while reading response header from upstream, client: 192.168.1.179, server: , request: "GET /admin/api.php?summary HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.1.10", referrer: "http://192.168.1.10/admin/"


==> /var/log/nginx/access.log <==
192.168.1.179 - - [01/Oct/2016:19:01:43 +0000] "GET /admin/api.php?summary HTTP/1.1" 200 128 "http://192.168.1.10/admin/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.41 Safari/537.36"

==> /var/log/nginx/error.log <==

2016/10/01 19:01:43 [error] 224#224: *1 FastCGI sent in stderr: "PHP message: PHP Warning: parse_ini_file(/etc/pihole/setupVars.conf): failed to open stream: No such file or directory in /var/www/html/admin/data.php on line 3" while reading response header from upstream, client: 192.168.1.179, server: , request: "GET /admin/api.php?summary HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", h
```ost: "192.168.1.10", referrer: "http://192.168.1.10/admin/"

**Comment by diginc** [comment]
That line 3 in data seems related to the summary of domains blocked functionality.  If ipv6 is on they divide the count by two, otherwise by 1.  Since that file doesn't exist in my docker yet it'll always be 1 which should be accurate because I'm pretty sure ipv6 blocking doesn't work in my docker yet (see #43).  For now I think I'll touch the file and leave it empty to make the warning go away.

Thanks for the report, seems like a minor warning but I'll keep an eye out for any more other critical usages of setupVars.txt that might require I actually add it into docker.

**Comment by srygaard** [comment]
Thanks, after running the following:

`docker exec pihole touch /etc/pihole/setupVars.conf
`

The error then slightly changes to:

`2016/10/01 21:49:52 [error] 221#221: *8 FastCGI sent in stderr: "PHP message: PHP Notice: Undefined index: piholeIPv6 in /var/www/html/admin/data.php on line 3" while reading response header from upstream, client: 192.168.1.3, server: , request: "GET /admin/api.php?summary HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.1.10", referrer: "http://192.168.1.10/admin/"
`

As a workaround on my system I ran the following:

` docker exec pihole /bin/sh -c "echo piholeIPv6= >> /etc/pihole/setupVars.conf"
`

which seems to have worked!
