### ISSUE TITLE
Pi-Hole fails after host restart

### ISSUE THREAD

**Issue by scottsweb** [diginc/docker-pi-hole#51]
I am running the latest build for arm (diginc/pi-hole:arm) and when restarting the host Pi-Hole fails to come back up. I have to login to the host, trash the container and start a new one. 

From the logs it looks to be an issue around:

```
Added ENV to php:
			"VIRTUAL_HOST" => "pihole.lan",
			"ServerIP" => "192.168.1.10",
```

When it fails the VIRTUAL_HOST and ServerIP appear twice. So I think they are getting set a second time when the container restarts. 

I create my container with the following:

```
docker run --restart=always -p 53:53/tcp -p 53:53/udp -p 8053:80 --cap-add=NET_ADMIN -e ServerIP="192.168.1.10" -e VIRTUAL_HOST="pihole.lan" --name pihole -v /var/log/pihole.log:/var/log/pihole.log -v /media/data/pihole/:/etc/pihole/ -d diginc/pi-hole:arm
```
Let me know if I can help debug further.

**Comment by diginc** [comment]
I was just wondering about this the other night...restarting containers
re-runs start and appends the lines I'm appending more than once.  My bad,
I'll get a hot fix in for this.

**Comment by scottsweb** [comment]
Amazing, thank you! 👍
