### ISSUE TITLE
DNS1 and DNS2 environment variables do not work as documented

### ISSUE THREAD

**Issue by gotiniens** [diginc/docker-pi-hole#55]
The documentation suggests that these variables set the upstream DNS server to use for resolving. Except after starting my image with these variables I get the following in /etc/dnsmasq.d/01-pihole.conf

`
server=8.8.8.8
server=8.8.4.4
`
I would expect the values of the environment variables.

**Comment by diginc** [comment]
Hey, good catch.  Sorry for the regression, I did not have a test around those variables but the fix I implemented does so this shouldn't happen again.  The new fixed version of the containers should be building now.
