### ISSUE TITLE
Fix build Docker

### ISSUE THREAD

**Issue by flamme-demon** [diginc/docker-pi-hole#63]
Hi,

Would it be possible to correct the build on docker?

Ex : https://hub.docker.com/r/diginc/pi-hole/builds/bwmmpbneso9vk45it3kuyji/

Thanks for your great work

**Comment by diginc** [comment]
Dockers support confirmed this is a bug on dockers side.  Builds that used
to work no longer work on hub due to an overlayFS bug.  There is a work
around of changing your build or building the images on your own nodes on
docker cloud, I opted for the 2nd choice.

**Comment by flamme-demon** [comment]
I passed with the cloud a build the DEBIAN version today.

I even try the version: Pi-hole Version v2.9.5 Web Interface Version v1.4.4.2

**Comment by dschaper** [comment]
The updated versions are a bonus, we neglected to bring diginc in on the release like we have in the past, and he's just seeing the release code at the same time as the rest of the net. Apologies for that oversight.

**Comment by diginc** [comment]
Oh, if we're talking about 2.9.5 then the new versions have a few variable additions / changes that require I update the docker's shell scripts a little.  I started yesterday but did not have time to iron out all the kinks.

**Comment by diginc** [comment]
Per the previously linked thread's update 5 days ago and confirmed by https://hub.docker.com/r/diginc/pi-hole/builds/ - it looks like docker fixed the issue with hub so me building the images in cloud is redundant, it was interesting to try out though.
