### ISSUE TITLE
"docker-pi-hole users update their docker images, not git code" why ?

### ISSUE THREAD

**Issue by thomasleveil** [diginc/docker-pi-hole#72]
The docker image [prevents](https://github.com/diginc/docker-pi-hole/blob/master/update.sh#L16) pi-hole updates through git. 

While I understand that a docker pull/restart does the job, why removing the ability to update through git? I would be fine with having my pi-hole update itself without restart the container, still knowing that in case of trouble I can always pull/rm/up a new container.

Maybe I'm missing something obvious?

**Comment by diginc** [comment]
I didn't choose to remove the ability to upgrade with git, the base debian and alpine docker images don't ship with git and I didn't see it as core to the functionality of pi-hole so it was left out.

It was the conscious choice to do things the docker way (small and concise) and avoiding unneeded installations & complexity (rolling upgrades).  If you look at pi-hole's issues a lot of them are upgrade related.  My base images are tested to have a base level of functionality whenever I push them out so anyone pulling and running them (the right way) is guaranteed to just work.  I'd like to keep it this way.  More on this topic [here ](https://github.com/diginc/docker-pi-hole#upgrading)and [here](https://github.com/diginc/docker-pi-hole/issues/49)

It also keeps the size of the images down by not adding unneeded features/programs, git in this case:

| image | before git (MB) | with git (MB) | increase (MB / %) |
| --- | --- | --- | --- |
| debian | 277.5 | 310 | 32.5 (8%) |
| alpine | 97.7 | 115.7 | 18 ( 5%) |

**Comment by diginc** [comment]
It is worth referencing the official documentation too...I didn't even realize I was practically quoting it for my reasoning :D

https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/avoid-installing-unnecessary-packages

**Comment by thomasleveil** [comment]
Thank you for sharing the reasoning behind those choices.

I am also aware of the docker recommendations and keep them in mind for my images, and I don't forget that those are recommendations, not strict rules. Having multiple processes in the pi-hole container is a bliss and makes my life (as a user) easier 👍  

Also thanks to your project, I discovered the python [testinfra](https://testinfra.readthedocs.io/en/latest/) module, and it's gold ;)

Thanks you for sharing your work and maintaining this image 💯
