### ISSUE TITLE
Set TimeZone 

### ISSUE THREAD

**Issue by alanrburns** [diginc/docker-pi-hole#74]
I have looked for an easy way to set the timezone but the container doesn't seem to have the tools needed to change it.
bash: dpkg-reconfigure: command not found

**Comment by diginc** [comment]
There is a more docker way to set your timezone. dpkg-reconfigure is not required and wouldn't even be available on my alpine version of this docker sadly.

Try a docker volume mount for /etc/localtime:

```
$ docker run --rm -it debian date
Wed Dec  7 15:01:32 UTC 2016
$ docker run --rm -it -v /etc/localtime:/etc/localtime debian date
Wed Dec  7 09:01:25 CST 2016
```

If you don't want your host's timezone check out the zones in /usr/share/zoneinfo

    docker run --rm -it -v /usr/share/zoneinfo/Australia/Sydney:/etc/localtime alpine date
Thu Dec  8 02:02:58 AEDT 2016

**Comment by 240ch** [comment]
Please excuse me for replying to this closed issue. I'd like to use my timezone in docker-pi-hole. Many docker containers seem to support the environment variable `TZ` as stated here: https://www.reddit.com/r/synology/comments/66apge/docker_timezone_setting_linkage_in_dsm_docker_gui/
Unfortunately, Synology users (which is what I am) can't bind the volume `/usr/...` to docker-containers through the Synology UI. Would it be possible to support the `TZ` environment variable in a future release of docker-pi-hole?
