### ISSUE TITLE
Issue Docker-pi-hole with extra hosts

### ISSUE THREAD

**Issue by parpaing** [diginc/docker-pi-hole#76]
Hi Experts, 

I'm trying to set up docker-pi-hole with some extra webapp like [here](https://github.com/diginc/docker-pi-hole/blob/master/jwilder-proxy-example-doco.yml).
Here's my compose file (jwilder/nginx-proxy, diginc/pi-hole:alpine and linuxserver/sabnzbd))](http://pastebin.com/vdHgzrDX)

Here's differents files, once composed up:
- [diginc/pi-hole:alpine /etc/hosts](http://pastebin.com/erMtAS4z)
- [diginc/pi-hole:alpine /etc/nginx/conf.d/default.conf](http://pastebin.com/VrncHepz)

What i have done wrong here ?
Please, advise

**Comment by diginc** [comment]
Lines 56 - 62 appear commented in your extra_hosts list, simply remove the # from the beginning of those lines.

**Comment by parpaing** [comment]
You're right 56 is not comment anymore, 57 to 63 remains commented.

With this, I still can't get http://pihole.htpc.lan/admin...
"/var/log/pi-hole.log" not talking anymore, so as "journactl -fxe -u pi-hole"

Here's dig command result ([http://pastebin.com/iTBUtTDy](http://pastebin.com/iTBUtTDy))

**Comment by diginc** [comment]
When you try to hit  http://pihole.htpc.lan/admin/ do you get new logs in `docker-compose logs proxy` ?

Another thing I noticed is line 18 should match the internal port, 8080, and not the external port 30003.

**Comment by parpaing** [comment]
I simplied the docker file, sabnzbd removed, 30003 corrected by 8080 ([Pi-hole yml](http://pastebin.com/KZgs5352))

No new logs accessing http://pihole.htcp.lan/admin/ ([journalctl -fxe](http://pastebin.com/eVXhTsHZ))

**Comment by diginc** [comment]
Looking over everything again I think I see the problem.  

In your dig it says `;; SERVER: 192.168.1.1#53(192.168.1.1)` - Are you using your docker pi-hole (192.168.1.124) as DNS currently?  Without the pihole DNS being active on the machine you're hitting http://pihole.htcp.lan/admin/ from , extra_hosts DNS records won't work.

what does `dig pihole.htpc.lan` (or nslookup) say ?  does http://192.168.1.124/admin/ work?

**Comment by parpaing** [comment]
http://192.168.1.124/admin/, http://127.0.0.1/admin/ and http://localhost/admin/ work 
http://192.168.1.1/admin/ doesn't work.

[dig pihole.htpc.lan](http://pastebin.com/QE5WaXcv)

**Comment by diginc** [comment]
what is in /etc/resolv.conf ?

have you done the router setup part of pi-hole's instructions yet?  https://discourse.pi-hole.net/t/how-do-i-configure-my-devices-to-use-pi-hole-as-their-dns-server/245

**Comment by parpaing** [comment]
Indeed, thank you for your support !
