### ISSUE TITLE
BUG: There is a new version of Pi Hole but he doesn't update.

### ISSUE THREAD

**Issue by mat1th** [diginc/docker-pi-hole#79]
Thanks for your nice Docker image! 

Pi hole did have a update a couple days ago but I can't update my docker. When I run the docker image it doesn't get the newest version of Pi hole. On the repository It gives also that it uses a older version of the master branche 'AdminLTE @ 3e6955d'. 

Could you update the Docker? 

Thanks!

**Comment by mat1th** [comment]
The docker script does work on the new version, but there are some new features that does not work in the docker. 

- [ ] Changing the networking in settings 
- [ ] Setting new/another DNS server in settings
- [ ] Change Interface appearance in settings

**Comment by diginc** [comment]
Heya, I started working on this yesterday but I haven't had time to iron out all the wrinkles yet, this being a major release there are quite a few.  I'll let you know when I have something finished.

**Comment by mat1th** [comment]
Nice, Thank you!

**Comment by diginc** [comment]
#84 fixes
