### ISSUE TITLE
New build for latest pihole updates/changes?

### ISSUE THREAD

**Issue by kylerw** [diginc/docker-pi-hole#81]

**Comment by diginc** [comment]
There's a pending bug-fix release coming, I'll a release cut after that is published so I don't have to make 2 releases back to back.

https://github.com/pi-hole/pi-hole/releases

Sorry for the delay.  I was busy over holidays and am getting back into the swing of things now.

**Comment by kylerw** [comment]
@diginc The shiny new updates/features got me... I'm impatient... sorry! I'll watch for the bug-fix and following docker update.

Thanks!
