### ISSUE TITLE
Latest Alpine Build: Admin Interface Not Loading

### ISSUE THREAD

**Issue by dbec** [diginc/docker-pi-hole#92]
Since rebuilding from the latest 'alpine', I get this error when trying to pull up admin page:
Failed Host Check: lvicpdnsp01.ingramcontent.com vs 10.10.46.39, , pi.hole, localhost, 10.10.46.39
(10.10.46.39 being our container's internal IP)

**Comment by diginc** [comment]
is lvicpdnsp01.ingramcontent.com/admin the address you use to access your pi-hole?
if so try setting '-e VIRTUAL_HOST=lvicpdnsp01.ingramcontent.com' in your docker run command

http://10.10.46.39/admin should work as an alternative too, unless you have a reverse proxy without pi-hole as your default site.

**Comment by dbec** [comment]
I confirmed that using the IP did work for getting to admin page, even before adding VIRTUAL_HOST to run command. I then added that and it works now via host name as well. Thanks! I'm puzzled as to why it had worked earlier without VIRTUAL_HOST.

**Comment by diginc** [comment]
I think the old version bailed out of the CORS check in one specific condition and let you through, or maybe my old alpine tag introduced a bug.  Seems the newest version does CORS checks properly so now the /admin page is a lot more secure 👍

Glad you got it working.
